CREATE TABLE IF NOT EXISTS "public"."seasons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "troop_number" character varying DEFAULT '0000'::character varying NOT NULL,
    "profile" "uuid" NOT NULL,
    "year" int NOT NULL,
    "publish_girl_request_form" boolean DEFAULT false NOT NULL,
    "girl_request_form_password" text
);


ALTER TABLE "public"."seasons" OWNER TO "postgres";


ALTER TABLE "public"."seasons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seasons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");

ALTER TABLE "public"."seasons" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Allow owners to manage their own seasons"
ON "public"."seasons"
FOR ALL
TO authenticated
USING ( profile = auth.uid() )
WITH CHECK ( profile = auth.uid() );
