CREATE TABLE IF NOT EXISTS "public"."seasons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "troop_number" character varying DEFAULT '0000'::character varying NOT NULL,
    "profile" "uuid" NOT NULL,
    "year" int NOT NULL,
    "publish_girl_request_form" boolean DEFAULT false
);


ALTER TABLE "public"."seasons" OWNER TO "postgres";


ALTER TABLE "public"."seasons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."seasons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "seasons_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") on delete cascade;

ALTER TABLE "public"."seasons" ENABLE ROW LEVEL SECURITY;

-- INSERT policy only needs WITH CHECK clause; USING is not applicable for INSERT operations
CREATE POLICY "Allow owners to insert their own seasons"
ON "public"."seasons"
FOR INSERT
TO authenticated
WITH CHECK ( profile = auth.uid() );
-- Note: SELECT, UPDATE, and DELETE policies for seasons are defined in 04-season-collaborators.sql
-- after the is_season_owner() and is_season_collaborator() functions are created

-- Allow anonymous users to read seasons
CREATE POLICY "Allow anonymous users to read seasons"
ON "public"."seasons"
FOR SELECT
TO anon
USING (true);