CREATE TABLE IF NOT EXISTS "public"."cookies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "price" double precision,
    "color" character varying,
    "profile" "uuid",
    "order" smallint,
    "abbreviation" character varying NOT NULL,
    "season" bigint DEFAULT '1'::bigint NOT NULL
);


ALTER TABLE "public"."cookies" OWNER TO "postgres";


ALTER TABLE "public"."cookies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cookies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");


ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id");


ALTER TABLE "public"."cookies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Allow users to delete their own data" ON "public"."cookies" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));
CREATE POLICY "Allow users to insert their own data" ON "public"."cookies" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));
CREATE POLICY "Allow users to update their own data" ON "public"."cookies" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));
CREATE POLICY "Allow users to view their own data" ON "public"."cookies" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));
