CREATE TABLE IF NOT EXISTS "public"."cookies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "price" double precision,
    "color" character varying,
    "profile" "uuid",
    "order" smallint,
    "abbreviation" character varying NOT NULL,
    "season" bigint DEFAULT '1'::bigint NOT NULL,
    "percent_of_sale" double precision,
    "is_virtual" boolean DEFAULT false,
    "overbooking_allowed" boolean DEFAULT true
);


ALTER TABLE "public"."cookies" OWNER TO "postgres";


ALTER TABLE "public"."cookies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cookies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") on delete cascade;


ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id") on delete cascade;


ALTER TABLE "public"."cookies" ENABLE ROW LEVEL SECURITY;


