CREATE TABLE IF NOT EXISTS "public"."sellers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "preferred_name" character varying,
    "season" bigint DEFAULT '1'::bigint NOT NULL
);


ALTER TABLE "public"."sellers" OWNER TO "postgres";


ALTER TABLE "public"."sellers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sellers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") on delete cascade;


ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id") on delete cascade;


ALTER TABLE "public"."sellers" ENABLE ROW LEVEL SECURITY;
