CREATE TABLE IF NOT EXISTS "public"."adults" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "preferred_name" character varying,
    "season" bigint DEFAULT '1'::bigint NOT NULL,
    "email" text,
    "phone" text,
    "sellers" bigint[] DEFAULT '{}'::bigint[] NOT NULL
);


ALTER TABLE "public"."adults" OWNER TO "postgres";


ALTER TABLE "public"."adults" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."adults_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."adults"
    ADD CONSTRAINT "adults_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."adults"
    ADD CONSTRAINT "adults_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") on delete cascade;


ALTER TABLE ONLY "public"."adults"
    ADD CONSTRAINT "adults_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id") on delete cascade;


ALTER TABLE "public"."adults" ENABLE ROW LEVEL SECURITY;


CREATE OR REPLACE FUNCTION public.remove_deleted_seller_from_adults()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.adults
    SET sellers = array_remove(sellers, OLD.id)
    WHERE OLD.id = ANY(sellers);

    RETURN OLD;
END;
$$;

CREATE TRIGGER remove_deleted_seller_from_adults_trigger
AFTER DELETE ON public.sellers
FOR EACH ROW
EXECUTE FUNCTION public.remove_deleted_seller_from_adults();
