CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "order_date" "date",
    "order_num" character varying,
    "to" bigint,
    "cookies" "jsonb",
    "profile" "uuid",
    "season" bigint DEFAULT '1'::bigint NOT NULL,
    "type" character varying,
    "status" character varying,
    "processed_date" "date",
    "notes" "text",
    "from" bigint,
    "supplier" "text"
);


ALTER TABLE "public"."orders" OWNER TO "postgres";


COMMENT ON COLUMN "public"."orders"."supplier" IS 'For all transactions from council, girls, and other troops';


ALTER TABLE "public"."orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") on delete cascade;


ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id") on delete cascade;

ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_to_fkey" FOREIGN KEY ("to") REFERENCES "public"."sellers"("id") on delete cascade;

ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_from_fkey" FOREIGN KEY ("from") REFERENCES "public"."sellers"("id") on delete cascade;

ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;

-- Allow public to insert cookie requests for published seasons
CREATE POLICY "Allow public to insert cookie requests"
ON "public"."orders"
FOR INSERT
TO anon
WITH CHECK (
    status = 'requested'
    AND type = 'T2G'
    AND "to" IN (SELECT id FROM public.seller_requests)
    AND EXISTS (
        SELECT 1 FROM public.sellers
        WHERE public.sellers.id = orders."to"
        AND public.sellers.season IN (
            SELECT season FROM public.seller_requests WHERE id = orders."to"
        )
    )
);
