-- Create payments table for tracking scout payments
CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "season" bigint DEFAULT '1'::bigint NOT NULL,
    "seller_id" bigint not null,
    "amount" decimal(10,2) not null,
    "payment_date" date not null,
    "notes" text,
    "type" character varying,
    constraint "payments_pkey" primary key ("id"),
    constraint "payments_profile_fkey" foreign key ("profile") references "public"."profiles"("id") on delete cascade,
    constraint "payments_season_fkey" foreign key ("season") references "public"."seasons"("id") on delete cascade,
    constraint "payments_seller_id_fkey" foreign key ("seller_id") references "public"."sellers"("id") on delete cascade
);

-- Enable row level security
alter table "public"."payments" enable row level security;

-- RLS policies for payments table
create policy "Allow users to view their own payments" on "public"."payments" for select to "authenticated" using ((( select "auth"."uid"() as "uid") = "profile"));
create policy "Allow users to insert their own payments" on "public"."payments" for insert to "authenticated" with check ((( select "auth"."uid"() as "uid") = "profile"));
create policy "Allow users to update their own payments" on "public"."payments" for update to "authenticated" using ((( select "auth"."uid"() as "uid") = "profile")) with check ((( select "auth"."uid"() as "uid") = "profile"));
create policy "Allow users to delete their own payments" on "public"."payments" for delete to "authenticated" using ((( select "auth"."uid"() as "uid") = "profile"));

-- Create indexes for better performance
create index "payments_profile_season_idx" on "public"."payments" using btree ("profile", "season");
create index "payments_seller_id_idx" on "public"."payments" using btree ("seller_id");