CREATE TABLE IF NOT EXISTS "public"."uploads" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "data" "jsonb",
    "profile" "uuid",
    "season" bigint DEFAULT '1'::bigint NOT NULL
);


ALTER TABLE "public"."uploads" OWNER TO "postgres";


COMMENT ON TABLE "public"."uploads" IS 'To hold big blobs of JSON objects from council provided systems';



ALTER TABLE "public"."uploads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."uploads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."uploads"
    ADD CONSTRAINT "uploads_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."uploads"
    ADD CONSTRAINT "uploads_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");


ALTER TABLE ONLY "public"."uploads"
    ADD CONSTRAINT "uploads_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id");


ALTER TABLE "public"."uploads" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Allow users to delete their own data" ON "public"."uploads" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));
CREATE POLICY "Allow users to insert their own data" ON "public"."uploads" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));
CREATE POLICY "Allow users to update their own data" ON "public"."uploads" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));
CREATE POLICY "Allow users to view their own data" ON "public"."uploads" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));
