-- Create booth_sales table
create table booth_sales (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  profile uuid references profiles(id) on delete cascade not null,
  season bigint references seasons(id) on delete cascade not null default 1,
  sale_date date not null,
  sale_time text,
  location text not null,
  scouts_attending jsonb, -- Array of scout names/IDs attending
  inventory_type text not null check (inventory_type in ('troop', 'scout')),
  expected_sales integer, -- Expected number of cookie boxes to be sold,
  predicted_cookies jsonb, -- Store predicted cookie quantities as JSON
  notes text,
  status text check (status is null or status in ('archived'))
);

-- Enable RLS
alter table booth_sales enable row level security;

-- Indexes for performance
create index booth_sales_profile_idx on booth_sales(profile);
create index booth_sales_season_idx on booth_sales(season);
create index booth_sales_date_idx on booth_sales(sale_date);