-- Create booth_sales table
create table booth_sales (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  profile uuid references profiles(id) on delete cascade not null,
  season bigint references seasons(id) on delete cascade not null default 1,
  sale_date date not null,
  sale_time time not null,
  location text not null,
  scouts_attending text[], -- Array of scout names/IDs attending
  inventory_type text not null check (inventory_type in ('troop', 'scout')),
  expected_sales_level text not null check (expected_sales_level in ('low', 'medium', 'high')),
  predicted_cookies jsonb, -- Store predicted cookie quantities as JSON
  notes text
);

-- Enable RLS
alter table booth_sales enable row level security;

-- RLS policies
create policy "Users can only see their own booth sales" on booth_sales for select using (auth.uid() = profile);
create policy "Users can insert their own booth sales" on booth_sales for insert with check (auth.uid() = profile);
create policy "Users can update their own booth sales" on booth_sales for update using (auth.uid() = profile);
create policy "Users can delete their own booth sales" on booth_sales for delete using (auth.uid() = profile);

-- Indexes for performance
create index booth_sales_profile_idx on booth_sales(profile);
create index booth_sales_season_idx on booth_sales(season);
create index booth_sales_date_idx on booth_sales(sale_date);