-- Create inventory_checks table
create table inventory_checks (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  profile uuid references profiles(id) on delete cascade not null,
  season bigint references seasons(id) on delete cascade not null default 1,
  check_date timestamp with time zone not null default now(),
  conducted_by text,
  physical_inventory jsonb not null,
  expected_inventory jsonb not null,
  discrepancies jsonb not null,
  total_discrepancies integer not null default 0,
  status text not null default 'completed',
  notes text
);

-- Enable RLS
alter table inventory_checks enable row level security;

-- Indexes for performance
create index inventory_checks_profile_idx on inventory_checks(profile);
create index inventory_checks_season_idx on inventory_checks(season);
create index inventory_checks_date_idx on inventory_checks(check_date);