-- can_edit... and can_view... columns not currently used in the app, but added for future flexibility
CREATE TABLE IF NOT EXISTS "public"."season_collaborators" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "season_id" bigint NOT NULL,
    "profile_id" uuid NOT NULL,
    "invited_by" uuid NOT NULL,
    "can_edit_booths" boolean DEFAULT false NOT NULL,
    "can_view_booths" boolean DEFAULT false NOT NULL,
    "can_edit_inventory_checks" boolean DEFAULT false NOT NULL,
    "can_view_inventory_checks" boolean DEFAULT false NOT NULL,
    CONSTRAINT "season_collaborators_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "season_collaborators_unique" UNIQUE ("season_id", "profile_id")
);

ALTER TABLE "public"."season_collaborators" OWNER TO "postgres";

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_season_id_fkey" 
    FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_profile_id_fkey" 
    FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_invited_by_fkey" 
    FOREIGN KEY ("invited_by") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE "public"."season_collaborators" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for season_collaborators
-- Allow season owners to insert collaborators
CREATE POLICY "Season owners can insert collaborators"
ON "public"."season_collaborators"
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
);

-- Allow season owners to update collaborators
CREATE POLICY "Season owners can update collaborators"
ON "public"."season_collaborators"
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
);

-- Allow season owners to delete collaborators
CREATE POLICY "Season owners can delete collaborators"
ON "public"."season_collaborators"
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
);

-- Allow season owners and collaborators to view collaborator records
CREATE POLICY "Season owners/collaborators can view collaborators"
ON "public"."season_collaborators"
FOR SELECT
TO authenticated
USING (
    profile_id = auth.uid() OR 
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
);

CREATE OR REPLACE FUNCTION public.is_season_collaborator(p_season_id bigint, p_profile_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.season_collaborators
    WHERE season_collaborators.season_id = p_season_id
      AND season_collaborators.profile_id = p_profile_id
  );
$$;

CREATE OR REPLACE FUNCTION public.is_season_owner(p_season_id bigint, p_profile_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1 FROM public.seasons
        WHERE seasons.id = p_season_id
          AND seasons.profile = p_profile_id
    );
$$;

ALTER FUNCTION "public"."is_season_collaborator" OWNER TO "postgres";

CREATE POLICY "Allow owners/collaborators to view their own cookies" ON public.cookies FOR SELECT TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to delete their own cookies" ON public.cookies FOR DELETE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to insert their own cookies" ON public.cookies FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to update their own cookies" ON public.cookies FOR UPDATE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to view their own sellers" ON public.sellers FOR SELECT TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to delete their own sellers" ON public.sellers FOR DELETE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to insert their own sellers" ON public.sellers FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to update their own sellers" ON public.sellers FOR UPDATE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to view their own payments" ON public.payments FOR SELECT TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to delete their own payments" ON public.payments FOR DELETE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to insert their own payments" ON public.payments FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to update their own payments" ON public.payments FOR UPDATE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to view their own boothsales" ON public.booth_sales FOR SELECT TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to delete their own boothsales" ON public.booth_sales FOR DELETE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to insert their own boothsales" ON public.booth_sales FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to update their own boothsales" ON public.booth_sales FOR UPDATE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to view their own inventory checks" ON public.inventory_checks FOR SELECT TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to delete their own inventory checks" ON public.inventory_checks FOR DELETE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to insert their own inventory checks" ON public.inventory_checks FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to update their own inventory checks" ON public.inventory_checks FOR UPDATE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to view their own orders" ON public.orders FOR SELECT TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to delete their own orders" ON public.orders FOR DELETE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to insert their own orders" ON public.orders FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
CREATE POLICY "Allow owners/collaborators to update their own orders" ON public.orders FOR UPDATE TO authenticated USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

-- Grant permissions to authenticated users
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."season_collaborators" TO "authenticated";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."season_collaborators" TO "service_role";

GRANT USAGE ON SEQUENCE "public"."season_collaborators_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."season_collaborators_id_seq" TO "service_role";