CREATE TABLE IF NOT EXISTS "public"."season_collaborators" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "season_id" bigint NOT NULL,
    "profile_id" uuid NOT NULL,
    "invited_by" uuid NOT NULL,
    "can_edit_booths" boolean DEFAULT false NOT NULL,
    "can_view_booths" boolean DEFAULT false NOT NULL,
    "can_edit_inventory_checks" boolean DEFAULT false NOT NULL,
    "can_view_inventory_checks" boolean DEFAULT false NOT NULL,
    CONSTRAINT "season_collaborators_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "season_collaborators_unique" UNIQUE ("season_id", "profile_id")
);

ALTER TABLE "public"."season_collaborators" OWNER TO "postgres";

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_season_id_fkey" 
    FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_profile_id_fkey" 
    FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_invited_by_fkey" 
    FOREIGN KEY ("invited_by") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE "public"."season_collaborators" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for season_collaborators
-- Allow season owners to manage collaborators
CREATE POLICY "Season owners can manage collaborators"
ON "public"."season_collaborators"
FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
);

-- Allow collaborators to view their own collaboration record
CREATE POLICY "Collaborators can view their own record"
ON "public"."season_collaborators"
FOR SELECT
TO authenticated
USING (profile_id = auth.uid());

CREATE OR REPLACE FUNCTION public.is_season_collaborator(p_season_id uuid, p_profile_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.season_collaborators
    WHERE season_collaborators.season_id = p_season_id
      AND season_collaborators.profile_id = p_profile_id
  );
$$;

ALTER FUNCTION "public"."is_season_collaborator" OWNER TO "postgres";

CREATE POLICY "Allow users to view their own seasons"
ON public.seasons
FOR SELECT
TO authenticated
USING (
  auth.uid() = profile
  OR public.is_season_collaborator(id, auth.uid())
);


CREATE POLICY "Allow users to view their own seasons"
ON "public"."seasons"
FOR SELECT
TO "authenticated" 
USING (
    (( SELECT "auth"."uid"() AS "uid") = "profile") 
    OR EXISTS (
        SELECT 1 FROM "season_collaborators"
        WHERE "season_collaborators"."season_id" = "seasons"."id" 
        AND "season_collaborators"."profile_id" = auth.uid()
    )
);

-- Grant permissions to authenticated users
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."season_collaborators" TO "authenticated";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."season_collaborators" TO "service_role";

GRANT USAGE ON SEQUENCE "public"."season_collaborators_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."season_collaborators_id_seq" TO "service_role";