-- Create deposits table for tracking bank deposits
CREATE TABLE IF NOT EXISTS "public"."deposits" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "season" bigint DEFAULT '1'::bigint NOT NULL,
    "amount" decimal(10,2) not null,
    "deposit_date" date not null,
    "notes" text,
    constraint "deposits_pkey" primary key ("id"),
    constraint "deposits_profile_fkey" foreign key ("profile") references "public"."profiles"("id") on delete cascade,
    constraint "deposits_season_fkey" foreign key ("season") references "public"."seasons"("id") on delete cascade
);

-- Enable row level security
alter table "public"."deposits" enable row level security;

-- Create indexes for better performance
create index "deposits_profile_season_idx" on "public"."deposits" using btree ("profile", "season");
create index "deposits_deposit_date_idx" on "public"."deposits" using btree ("deposit_date");

-- RLS Policies for deposits
CREATE POLICY "Allow owners/collaborators to view their own deposits" 
ON public.deposits 
FOR SELECT 
TO authenticated 
USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to delete their own deposits" 
ON public.deposits 
FOR DELETE 
TO authenticated 
USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to insert their own deposits" 
ON public.deposits 
FOR INSERT 
TO authenticated 
WITH CHECK ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );

CREATE POLICY "Allow owners/collaborators to update their own deposits" 
ON public.deposits 
FOR UPDATE 
TO authenticated 
USING ( public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid()) );
