CREATE TABLE IF NOT EXISTS "public"."seller_permissions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "collaborator_id" bigint NOT NULL,
    "seller_id" bigint NOT NULL,
    "permission_level" text NOT NULL CHECK (permission_level IN ('none', 'view', 'request', 'edit')),
    CONSTRAINT "seller_permissions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "seller_permissions_unique" UNIQUE ("collaborator_id", "seller_id")
);

ALTER TABLE "public"."seller_permissions" OWNER TO "postgres";

ALTER TABLE ONLY "public"."seller_permissions"
    ADD CONSTRAINT "seller_permissions_collaborator_id_fkey" 
    FOREIGN KEY ("collaborator_id") REFERENCES "public"."season_collaborators"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."seller_permissions"
    ADD CONSTRAINT "seller_permissions_seller_id_fkey" 
    FOREIGN KEY ("seller_id") REFERENCES "public"."sellers"("id") ON DELETE CASCADE;

ALTER TABLE "public"."seller_permissions" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for seller_permissions
-- Allow season owners to manage seller permissions
CREATE POLICY "Season owners can manage seller permissions"
ON "public"."seller_permissions"
FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM season_collaborators 
        JOIN seasons ON seasons.id = season_collaborators.season_id
        WHERE season_collaborators.id = seller_permissions.collaborator_id 
        AND seasons.profile = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM season_collaborators 
        JOIN seasons ON seasons.id = season_collaborators.season_id
        WHERE season_collaborators.id = seller_permissions.collaborator_id 
        AND seasons.profile = auth.uid()
    )
);

-- Allow collaborators to view their own permissions
CREATE POLICY "Collaborators can view their own permissions"
ON "public"."seller_permissions"
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM season_collaborators 
        WHERE season_collaborators.id = seller_permissions.collaborator_id 
        AND season_collaborators.profile_id = auth.uid()
    )
);

-- Grant permissions to authenticated users
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."seller_permissions" TO "authenticated";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."seller_permissions" TO "service_role";

GRANT USAGE ON SEQUENCE "public"."seller_permissions_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."seller_permissions_id_seq" TO "service_role";

