CREATE TABLE IF NOT EXISTS "public"."badges" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "name" character varying NOT NULL,
    "url" text,
    "program_level" character varying NOT NULL,
    "season" bigint NOT NULL,
    CONSTRAINT "badges_program_level_check" CHECK (
        ("program_level")::text = ANY (
            ARRAY[
                'daisy'::character varying,
                'brownie'::character varying,
                'junior'::character varying,
                'cadette'::character varying,
                'senior'::character varying,
                'ambassador'::character varying
            ]::text[]
        )
    )
);


ALTER TABLE "public"."badges" OWNER TO "postgres";


ALTER TABLE "public"."badges" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."badges_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


ALTER TABLE ONLY "public"."badges"
    ADD CONSTRAINT "badges_pkey" PRIMARY KEY ("id");


ALTER TABLE ONLY "public"."badges"
    ADD CONSTRAINT "badges_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;


ALTER TABLE ONLY "public"."badges"
    ADD CONSTRAINT "badges_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id") ON DELETE CASCADE;


ALTER TABLE "public"."badges" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sellers"
    ADD COLUMN IF NOT EXISTS "badges_earned" bigint[] DEFAULT '{}'::bigint[] NOT NULL;


ALTER TABLE "public"."sellers"
    ADD COLUMN IF NOT EXISTS "badges_received" bigint[] DEFAULT '{}'::bigint[] NOT NULL;


CREATE OR REPLACE FUNCTION public.remove_deleted_badge_from_sellers()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.sellers
    SET
        badges_earned = array_remove(badges_earned, OLD.id),
        badges_received = array_remove(badges_received, OLD.id)
    WHERE OLD.id = ANY(badges_earned) OR OLD.id = ANY(badges_received);

    RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


DROP TRIGGER IF EXISTS remove_deleted_badge_from_sellers_trigger ON public.badges;


CREATE TRIGGER remove_deleted_badge_from_sellers_trigger
    AFTER DELETE ON public.badges
    FOR EACH ROW
    EXECUTE FUNCTION public.remove_deleted_badge_from_sellers();


CREATE POLICY "Allow owners/collaborators to view their own badges" ON public.badges FOR SELECT TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to delete their own badges" ON public.badges FOR DELETE TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to insert their own badges" ON public.badges FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to update their own badges" ON public.badges FOR UPDATE TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
