

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() 
    RETURNS "trigger"
    LANGUAGE "plpgsql" 
    SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  RAISE LOG 'Trigger function started for user: %', NEW.id;
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

CREATE TRIGGER on_auth_user_insert
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.handle_new_user();
SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."cookies" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "price" double precision,
    "color" character varying,
    "profile" "uuid",
    "order" smallint,
    "abbreviation" character varying NOT NULL,
    "season" bigint DEFAULT '1'::bigint NOT NULL
);


ALTER TABLE "public"."cookies" OWNER TO "postgres";


ALTER TABLE "public"."cookies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cookies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."orders" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "order_date" "date",
    "order_num" character varying,
    "to" bigint,
    "cookies" "jsonb",
    "profile" "uuid",
    "season" bigint DEFAULT '1'::bigint NOT NULL,
    "type" character varying,
    "status" character varying,
    "processed_date" "date",
    "notes" "text",
    "from" bigint,
    "supplier" "text"
);


ALTER TABLE "public"."orders" OWNER TO "postgres";


COMMENT ON COLUMN "public"."orders"."supplier" IS 'For orders that increase the troop supply from sources outside the troop (ie council cupboards, other troops)';



ALTER TABLE "public"."orders" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."orders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "updated_at" timestamp with time zone,
    "username" "text",
    "full_name" "text",
    "avatar_url" "text",
    "website" "text",
    "state" "jsonb",
    "season" bigint,
    CONSTRAINT "username_length" CHECK (("char_length"("username") >= 3))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."seasons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "troop_number" character varying DEFAULT '0000'::character varying NOT NULL,
    "profile" "uuid" NOT NULL,
    "year" "date" DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."seasons" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sellers" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "first_name" character varying NOT NULL,
    "last_name" character varying NOT NULL,
    "preferred_name" character varying,
    "season" bigint DEFAULT '1'::bigint NOT NULL
);


ALTER TABLE "public"."sellers" OWNER TO "postgres";


ALTER TABLE "public"."sellers" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sellers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."seasons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."troops_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."uploads" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "data" "jsonb",
    "profile" "uuid",
    "season" bigint DEFAULT '1'::bigint NOT NULL
);


ALTER TABLE "public"."uploads" OWNER TO "postgres";


COMMENT ON TABLE "public"."uploads" IS 'To hold big blobs of JSON objects from council provided systems';



ALTER TABLE "public"."uploads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."uploads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "troops_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."uploads"
    ADD CONSTRAINT "uploads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."cookies"
    ADD CONSTRAINT "cookies_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id");



ALTER TABLE ONLY "public"."orders"
    ADD CONSTRAINT "orders_to_fkey" FOREIGN KEY ("to") REFERENCES "public"."sellers"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id");



ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."sellers"
    ADD CONSTRAINT "sellers_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id");



ALTER TABLE ONLY "public"."seasons"
    ADD CONSTRAINT "troops_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."uploads"
    ADD CONSTRAINT "uploads_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."uploads"
    ADD CONSTRAINT "uploads_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id");



CREATE POLICY "Allow users to delete their own data" ON "public"."cookies" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to delete their own data" ON "public"."orders" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to delete their own data" ON "public"."seasons" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to delete their own data" ON "public"."sellers" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to delete their own data" ON "public"."uploads" FOR DELETE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to insert their own data" ON "public"."cookies" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to insert their own data" ON "public"."orders" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to insert their own data" ON "public"."seasons" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to insert their own data" ON "public"."sellers" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to insert their own data" ON "public"."uploads" FOR INSERT TO "authenticated" WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to update their own data" ON "public"."cookies" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to update their own data" ON "public"."orders" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to update their own data" ON "public"."seasons" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to update their own data" ON "public"."sellers" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to update their own data" ON "public"."uploads" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to view their own data" ON "public"."cookies" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to view their own data" ON "public"."orders" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to view their own data" ON "public"."seasons" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to view their own data" ON "public"."sellers" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Allow users to view their own data" ON "public"."uploads" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "profile"));



CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Users can insert their own profile." ON "public"."profiles" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Users can update own profile." ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



ALTER TABLE "public"."cookies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."orders" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."seasons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sellers" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."uploads" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



























GRANT ALL ON TABLE "public"."cookies" TO "anon";
GRANT ALL ON TABLE "public"."cookies" TO "authenticated";
GRANT ALL ON TABLE "public"."cookies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cookies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cookies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cookies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."orders" TO "anon";
GRANT ALL ON TABLE "public"."orders" TO "authenticated";
GRANT ALL ON TABLE "public"."orders" TO "service_role";



GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."orders_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."seasons" TO "anon";
GRANT ALL ON TABLE "public"."seasons" TO "authenticated";
GRANT ALL ON TABLE "public"."seasons" TO "service_role";



GRANT ALL ON TABLE "public"."sellers" TO "anon";
GRANT ALL ON TABLE "public"."sellers" TO "authenticated";
GRANT ALL ON TABLE "public"."sellers" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sellers_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sellers_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sellers_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."troops_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."troops_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."troops_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."uploads" TO "anon";
GRANT ALL ON TABLE "public"."uploads" TO "authenticated";
GRANT ALL ON TABLE "public"."uploads" TO "service_role";



GRANT ALL ON SEQUENCE "public"."uploads_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."uploads_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."uploads_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
