create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "season" bigint not null default '1'::bigint,
    "seller_id" bigint not null,
    "amount" numeric(10,2) not null,
    "payment_date" date not null,
    "notes" text
);


alter table "public"."payments" enable row level security;

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);

CREATE INDEX payments_profile_season_idx ON public.payments USING btree (profile, season);

CREATE INDEX payments_seller_id_idx ON public.payments USING btree (seller_id);

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."payments" add constraint "payments_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_profile_fkey";

alter table "public"."payments" add constraint "payments_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) ON DELETE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_season_fkey";

alter table "public"."payments" add constraint "payments_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES sellers(id) ON DELETE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_seller_id_fkey";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";

create policy "Allow users to delete their own payments"
on "public"."payments"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to insert their own payments"
on "public"."payments"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to update their own payments"
on "public"."payments"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to view their own payments"
on "public"."payments"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));



