create extension if not exists "pgjwt" with schema "extensions";


create table "public"."cookies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "price" double precision,
    "color" character varying,
    "profile" uuid,
    "order" smallint,
    "abbreviation" character varying not null,
    "season" bigint not null default '1'::bigint
);


alter table "public"."cookies" enable row level security;

create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "order_date" date,
    "order_num" character varying,
    "to" bigint,
    "cookies" jsonb,
    "profile" uuid,
    "season" bigint not null default '1'::bigint,
    "type" character varying,
    "status" character varying,
    "processed_date" date,
    "notes" text,
    "from" bigint,
    "supplier" text
);


alter table "public"."orders" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone,
    "display_name" text,
    "state" jsonb,
    "season" bigint
);


alter table "public"."profiles" enable row level security;

create table "public"."seasons" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "troop_number" character varying not null default '0000'::character varying,
    "profile" uuid not null,
    "year" date not null default now()
);


alter table "public"."seasons" enable row level security;

create table "public"."sellers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "first_name" character varying not null,
    "last_name" character varying not null,
    "preferred_name" character varying,
    "season" bigint not null default '1'::bigint
);


alter table "public"."sellers" enable row level security;

create table "public"."uploads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "data" jsonb,
    "profile" uuid,
    "season" bigint not null default '1'::bigint
);


alter table "public"."uploads" enable row level security;

CREATE UNIQUE INDEX cookies_pkey ON public.cookies USING btree (id);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX seasons_pkey ON public.seasons USING btree (id);

CREATE UNIQUE INDEX sellers_pkey ON public.sellers USING btree (id);

CREATE UNIQUE INDEX uploads_pkey ON public.uploads USING btree (id);

alter table "public"."cookies" add constraint "cookies_pkey" PRIMARY KEY using index "cookies_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."seasons" add constraint "seasons_pkey" PRIMARY KEY using index "seasons_pkey";

alter table "public"."sellers" add constraint "sellers_pkey" PRIMARY KEY using index "sellers_pkey";

alter table "public"."uploads" add constraint "uploads_pkey" PRIMARY KEY using index "uploads_pkey";

alter table "public"."cookies" add constraint "cookies_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) not valid;

alter table "public"."cookies" validate constraint "cookies_profile_fkey";

alter table "public"."cookies" add constraint "cookies_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) not valid;

alter table "public"."cookies" validate constraint "cookies_season_fkey";

alter table "public"."orders" add constraint "orders_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) not valid;

alter table "public"."orders" validate constraint "orders_profile_fkey";

alter table "public"."orders" add constraint "orders_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) not valid;

alter table "public"."orders" validate constraint "orders_season_fkey";

alter table "public"."orders" add constraint "orders_to_fkey" FOREIGN KEY ("to") REFERENCES sellers(id) not valid;

alter table "public"."orders" validate constraint "orders_to_fkey";

alter table "public"."profiles" add constraint "display_name" CHECK ((char_length(display_name) >= 1)) not valid;

alter table "public"."profiles" validate constraint "display_name";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."seasons" add constraint "seasons_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) not valid;

alter table "public"."seasons" validate constraint "seasons_profile_fkey";

alter table "public"."sellers" add constraint "sellers_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) not valid;

alter table "public"."sellers" validate constraint "sellers_profile_fkey";

alter table "public"."sellers" add constraint "sellers_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) not valid;

alter table "public"."sellers" validate constraint "sellers_season_fkey";

alter table "public"."uploads" add constraint "uploads_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) not valid;

alter table "public"."uploads" validate constraint "uploads_profile_fkey";

alter table "public"."uploads" add constraint "uploads_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) not valid;

alter table "public"."uploads" validate constraint "uploads_season_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$function$
;

grant delete on table "public"."cookies" to "anon";

grant insert on table "public"."cookies" to "anon";

grant references on table "public"."cookies" to "anon";

grant select on table "public"."cookies" to "anon";

grant trigger on table "public"."cookies" to "anon";

grant truncate on table "public"."cookies" to "anon";

grant update on table "public"."cookies" to "anon";

grant delete on table "public"."cookies" to "authenticated";

grant insert on table "public"."cookies" to "authenticated";

grant references on table "public"."cookies" to "authenticated";

grant select on table "public"."cookies" to "authenticated";

grant trigger on table "public"."cookies" to "authenticated";

grant truncate on table "public"."cookies" to "authenticated";

grant update on table "public"."cookies" to "authenticated";

grant delete on table "public"."cookies" to "service_role";

grant insert on table "public"."cookies" to "service_role";

grant references on table "public"."cookies" to "service_role";

grant select on table "public"."cookies" to "service_role";

grant trigger on table "public"."cookies" to "service_role";

grant truncate on table "public"."cookies" to "service_role";

grant update on table "public"."cookies" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."seasons" to "anon";

grant insert on table "public"."seasons" to "anon";

grant references on table "public"."seasons" to "anon";

grant select on table "public"."seasons" to "anon";

grant trigger on table "public"."seasons" to "anon";

grant truncate on table "public"."seasons" to "anon";

grant update on table "public"."seasons" to "anon";

grant delete on table "public"."seasons" to "authenticated";

grant insert on table "public"."seasons" to "authenticated";

grant references on table "public"."seasons" to "authenticated";

grant select on table "public"."seasons" to "authenticated";

grant trigger on table "public"."seasons" to "authenticated";

grant truncate on table "public"."seasons" to "authenticated";

grant update on table "public"."seasons" to "authenticated";

grant delete on table "public"."seasons" to "service_role";

grant insert on table "public"."seasons" to "service_role";

grant references on table "public"."seasons" to "service_role";

grant select on table "public"."seasons" to "service_role";

grant trigger on table "public"."seasons" to "service_role";

grant truncate on table "public"."seasons" to "service_role";

grant update on table "public"."seasons" to "service_role";

grant delete on table "public"."sellers" to "anon";

grant insert on table "public"."sellers" to "anon";

grant references on table "public"."sellers" to "anon";

grant select on table "public"."sellers" to "anon";

grant trigger on table "public"."sellers" to "anon";

grant truncate on table "public"."sellers" to "anon";

grant update on table "public"."sellers" to "anon";

grant delete on table "public"."sellers" to "authenticated";

grant insert on table "public"."sellers" to "authenticated";

grant references on table "public"."sellers" to "authenticated";

grant select on table "public"."sellers" to "authenticated";

grant trigger on table "public"."sellers" to "authenticated";

grant truncate on table "public"."sellers" to "authenticated";

grant update on table "public"."sellers" to "authenticated";

grant delete on table "public"."sellers" to "service_role";

grant insert on table "public"."sellers" to "service_role";

grant references on table "public"."sellers" to "service_role";

grant select on table "public"."sellers" to "service_role";

grant trigger on table "public"."sellers" to "service_role";

grant truncate on table "public"."sellers" to "service_role";

grant update on table "public"."sellers" to "service_role";

grant delete on table "public"."uploads" to "anon";

grant insert on table "public"."uploads" to "anon";

grant references on table "public"."uploads" to "anon";

grant select on table "public"."uploads" to "anon";

grant trigger on table "public"."uploads" to "anon";

grant truncate on table "public"."uploads" to "anon";

grant update on table "public"."uploads" to "anon";

grant delete on table "public"."uploads" to "authenticated";

grant insert on table "public"."uploads" to "authenticated";

grant references on table "public"."uploads" to "authenticated";

grant select on table "public"."uploads" to "authenticated";

grant trigger on table "public"."uploads" to "authenticated";

grant truncate on table "public"."uploads" to "authenticated";

grant update on table "public"."uploads" to "authenticated";

grant delete on table "public"."uploads" to "service_role";

grant insert on table "public"."uploads" to "service_role";

grant references on table "public"."uploads" to "service_role";

grant select on table "public"."uploads" to "service_role";

grant trigger on table "public"."uploads" to "service_role";

grant truncate on table "public"."uploads" to "service_role";

grant update on table "public"."uploads" to "service_role";

create policy "Allow users to delete their own data"
on "public"."cookies"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to insert their own data"
on "public"."cookies"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to update their own data"
on "public"."cookies"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to view their own data"
on "public"."cookies"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to delete their own data"
on "public"."orders"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to insert their own data"
on "public"."orders"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to update their own data"
on "public"."orders"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to view their own data"
on "public"."orders"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Public profiles are viewable by everyone."
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "Users can insert their own profile."
on "public"."profiles"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = id));


create policy "Users can update own profile."
on "public"."profiles"
as permissive
for update
to public
using ((( SELECT auth.uid() AS uid) = id));


create policy "Allow users to delete their own data"
on "public"."seasons"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to insert their own data"
on "public"."seasons"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to update their own data"
on "public"."seasons"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to view their own data"
on "public"."seasons"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to delete their own data"
on "public"."sellers"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to insert their own data"
on "public"."sellers"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to update their own data"
on "public"."sellers"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to view their own data"
on "public"."sellers"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to delete their own data"
on "public"."uploads"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to insert their own data"
on "public"."uploads"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to update their own data"
on "public"."uploads"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));


create policy "Allow users to view their own data"
on "public"."uploads"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));



