drop policy "Users can delete their own booth sales" on "public"."booth_sales";

drop policy "Users can insert their own booth sales" on "public"."booth_sales";

drop policy "Users can only see their own booth sales" on "public"."booth_sales";

drop policy "Users can update their own booth sales" on "public"."booth_sales";

drop policy "Allow users to delete their own data" on "public"."cookies";

drop policy "Allow users to insert their own data" on "public"."cookies";

drop policy "Allow users to update their own data" on "public"."cookies";

drop policy "Allow users to view their own data" on "public"."cookies";

drop policy "Users can delete their own inventory checks" on "public"."inventory_checks";

drop policy "Users can insert their own inventory checks" on "public"."inventory_checks";

drop policy "Users can only see their own inventory checks" on "public"."inventory_checks";

drop policy "Users can update their own inventory checks" on "public"."inventory_checks";

drop policy "Allow users to delete their own data" on "public"."orders";

drop policy "Allow users to insert their own data" on "public"."orders";

drop policy "Allow users to update their own data" on "public"."orders";

drop policy "Allow users to view their own data" on "public"."orders";

drop policy "Allow users to delete their own payments" on "public"."payments";

drop policy "Allow users to insert their own payments" on "public"."payments";

drop policy "Allow users to update their own payments" on "public"."payments";

drop policy "Allow users to view their own payments" on "public"."payments";

drop policy "Allow users to delete their own data" on "public"."seasons";

drop policy "Allow users to insert their own data" on "public"."seasons";

drop policy "Allow users to update their own data" on "public"."seasons";

drop policy "Allow users to view their own data" on "public"."seasons";

drop policy "Allow users to delete their own data" on "public"."sellers";

drop policy "Allow users to insert their own data" on "public"."sellers";

drop policy "Allow users to update their own data" on "public"."sellers";

drop policy "Allow users to view their own data" on "public"."sellers";


  create table "public"."season_collaborators" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "season_id" bigint not null,
    "profile_id" uuid not null,
    "invited_by" uuid not null,
    "can_edit_booths" boolean not null default false,
    "can_view_booths" boolean not null default false,
    "can_edit_inventory_checks" boolean not null default false,
    "can_view_inventory_checks" boolean not null default false
      );


alter table "public"."season_collaborators" enable row level security;

CREATE UNIQUE INDEX season_collaborators_pkey ON public.season_collaborators USING btree (id);

CREATE UNIQUE INDEX season_collaborators_unique ON public.season_collaborators USING btree (season_id, profile_id);

alter table "public"."season_collaborators" add constraint "season_collaborators_pkey" PRIMARY KEY using index "season_collaborators_pkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_invited_by_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_profile_id_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_season_id_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_unique" UNIQUE using index "season_collaborators_unique";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.is_season_collaborator(p_season_id bigint, p_profile_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path = ''
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.season_collaborators
    WHERE season_collaborators.season_id = p_season_id
      AND season_collaborators.profile_id = p_profile_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_season_owner(p_season_id bigint, p_profile_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path = ''
AS $function$
    SELECT EXISTS (
        SELECT 1 FROM public.seasons
        WHERE seasons.id = p_season_id
          AND seasons.profile = p_profile_id
    );
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$function$
;

grant delete on table "public"."season_collaborators" to "anon";

grant insert on table "public"."season_collaborators" to "anon";

grant references on table "public"."season_collaborators" to "anon";

grant select on table "public"."season_collaborators" to "anon";

grant trigger on table "public"."season_collaborators" to "anon";

grant truncate on table "public"."season_collaborators" to "anon";

grant update on table "public"."season_collaborators" to "anon";

grant delete on table "public"."season_collaborators" to "authenticated";

grant insert on table "public"."season_collaborators" to "authenticated";

grant references on table "public"."season_collaborators" to "authenticated";

grant select on table "public"."season_collaborators" to "authenticated";

grant trigger on table "public"."season_collaborators" to "authenticated";

grant truncate on table "public"."season_collaborators" to "authenticated";

grant update on table "public"."season_collaborators" to "authenticated";

grant delete on table "public"."season_collaborators" to "service_role";

grant insert on table "public"."season_collaborators" to "service_role";

grant references on table "public"."season_collaborators" to "service_role";

grant select on table "public"."season_collaborators" to "service_role";

grant trigger on table "public"."season_collaborators" to "service_role";

grant truncate on table "public"."season_collaborators" to "service_role";

grant update on table "public"."season_collaborators" to "service_role";


  create policy "Allow owners/collaborators to delete their own boothsales"
  on "public"."booth_sales"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own boothsales"
  on "public"."booth_sales"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own boothsales"
  on "public"."booth_sales"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own boothsales"
  on "public"."booth_sales"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to delete their own cookies"
  on "public"."cookies"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own cookies"
  on "public"."cookies"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own cookies"
  on "public"."cookies"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own cookies"
  on "public"."cookies"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to delete their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to delete their own orders"
  on "public"."orders"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own orders"
  on "public"."orders"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own orders"
  on "public"."orders"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own orders"
  on "public"."orders"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to delete their own payments"
  on "public"."payments"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own payments"
  on "public"."payments"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own payments"
  on "public"."payments"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own payments"
  on "public"."payments"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Collaborators can view their own record"
  on "public"."season_collaborators"
  as permissive
  for select
  to authenticated
using ((profile_id = auth.uid()));



  create policy "Season owners can manage collaborators"
  on "public"."season_collaborators"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = auth.uid())))));



  create policy "Allow owners to manage their own seasons"
  on "public"."seasons"
  as permissive
  for all
  to authenticated
using ((profile = auth.uid()))
with check ((profile = auth.uid()));



  create policy "Allow owners/collaborators to delete their own seasons"
  on "public"."seasons"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(id, auth.uid()) OR public.is_season_collaborator(id, auth.uid())));



  create policy "Allow owners/collaborators to update their own seasons"
  on "public"."seasons"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(id, auth.uid()) OR public.is_season_collaborator(id, auth.uid())));



  create policy "Allow owners/collaborators to view their own seasons"
  on "public"."seasons"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(id, auth.uid()) OR public.is_season_collaborator(id, auth.uid())));



  create policy "Allow owners/collaborators to delete their own sellers"
  on "public"."sellers"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own sellers"
  on "public"."sellers"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own sellers"
  on "public"."sellers"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own sellers"
  on "public"."sellers"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));


CREATE TRIGGER on_auth_user_insert AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


