-- Create season_collaborators table
CREATE TABLE IF NOT EXISTS "public"."season_collaborators" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "season_id" bigint NOT NULL,
    "profile_id" uuid NOT NULL,
    "invited_by" uuid NOT NULL,
    "can_edit_booths" boolean DEFAULT false NOT NULL,
    "can_view_booths" boolean DEFAULT false NOT NULL,
    "can_edit_inventory_checks" boolean DEFAULT false NOT NULL,
    "can_view_inventory_checks" boolean DEFAULT false NOT NULL,
    CONSTRAINT "season_collaborators_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "season_collaborators_unique" UNIQUE ("season_id", "profile_id")
);

ALTER TABLE "public"."season_collaborators" OWNER TO "postgres";

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_season_id_fkey" 
    FOREIGN KEY ("season_id") REFERENCES "public"."seasons"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_profile_id_fkey" 
    FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."season_collaborators"
    ADD CONSTRAINT "season_collaborators_invited_by_fkey" 
    FOREIGN KEY ("invited_by") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

-- Create seller_permissions table for per-girl permissions
CREATE TABLE IF NOT EXISTS "public"."seller_permissions" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "collaborator_id" bigint NOT NULL,
    "seller_id" bigint NOT NULL,
    "permission_level" text NOT NULL CHECK (permission_level IN ('none', 'view', 'request', 'edit')),
    CONSTRAINT "seller_permissions_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "seller_permissions_unique" UNIQUE ("collaborator_id", "seller_id")
);

ALTER TABLE "public"."seller_permissions" OWNER TO "postgres";

ALTER TABLE ONLY "public"."seller_permissions"
    ADD CONSTRAINT "seller_permissions_collaborator_id_fkey" 
    FOREIGN KEY ("collaborator_id") REFERENCES "public"."season_collaborators"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."seller_permissions"
    ADD CONSTRAINT "seller_permissions_seller_id_fkey" 
    FOREIGN KEY ("seller_id") REFERENCES "public"."sellers"("id") ON DELETE CASCADE;

-- Enable Row Level Security
ALTER TABLE "public"."season_collaborators" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."seller_permissions" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for season_collaborators
-- Allow season owners to manage collaborators
CREATE POLICY "Season owners can manage collaborators"
ON "public"."season_collaborators"
FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM seasons 
        WHERE seasons.id = season_collaborators.season_id 
        AND seasons.profile = auth.uid()
    )
);

-- Allow collaborators to view their own collaboration record
CREATE POLICY "Collaborators can view their own record"
ON "public"."season_collaborators"
FOR SELECT
TO authenticated
USING (profile_id = auth.uid());

-- RLS Policies for seller_permissions
-- Allow season owners to manage seller permissions
CREATE POLICY "Season owners can manage seller permissions"
ON "public"."seller_permissions"
FOR ALL
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM season_collaborators 
        JOIN seasons ON seasons.id = season_collaborators.season_id
        WHERE season_collaborators.id = seller_permissions.collaborator_id 
        AND seasons.profile = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM season_collaborators 
        JOIN seasons ON seasons.id = season_collaborators.season_id
        WHERE season_collaborators.id = seller_permissions.collaborator_id 
        AND seasons.profile = auth.uid()
    )
);

-- Allow collaborators to view their own permissions
CREATE POLICY "Collaborators can view their own permissions"
ON "public"."seller_permissions"
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM season_collaborators 
        WHERE season_collaborators.id = seller_permissions.collaborator_id 
        AND season_collaborators.profile_id = auth.uid()
    )
);

-- Update seasons RLS to allow collaborators to view seasons they're invited to
DROP POLICY IF EXISTS "Allow users to view their own data" ON "public"."seasons";

CREATE POLICY "Allow users to view their own seasons"
ON "public"."seasons"
FOR SELECT
TO authenticated
USING (
    profile = auth.uid() 
    OR EXISTS (
        SELECT 1 FROM season_collaborators 
        WHERE season_collaborators.season_id = seasons.id 
        AND season_collaborators.profile_id = auth.uid()
    )
);

-- Grant permissions to authenticated users
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."season_collaborators" TO "authenticated";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."season_collaborators" TO "service_role";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."seller_permissions" TO "authenticated";

GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE 
ON TABLE "public"."seller_permissions" TO "service_role";

GRANT USAGE ON SEQUENCE "public"."season_collaborators_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."season_collaborators_id_seq" TO "service_role";

GRANT USAGE ON SEQUENCE "public"."seller_permissions_id_seq" TO "authenticated";
GRANT USAGE ON SEQUENCE "public"."seller_permissions_id_seq" TO "service_role";
