create table "public"."inventory_checks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid not null,
    "season" bigint not null default 1,
    "check_date" timestamp with time zone not null default now(),
    "conducted_by" text,
    "physical_inventory" jsonb not null,
    "expected_inventory" jsonb not null,
    "discrepancies" jsonb not null,
    "total_discrepancies" integer not null default 0,
    "status" text not null default 'completed',
    "notes" text
);


alter table "public"."inventory_checks" enable row level security;

CREATE INDEX inventory_checks_date_idx ON public.inventory_checks USING btree (check_date);

CREATE UNIQUE INDEX inventory_checks_pkey ON public.inventory_checks USING btree (id);

CREATE INDEX inventory_checks_profile_idx ON public.inventory_checks USING btree (profile);

CREATE INDEX inventory_checks_season_idx ON public.inventory_checks USING btree (season);

alter table "public"."inventory_checks" add constraint "inventory_checks_pkey" PRIMARY KEY using index "inventory_checks_pkey";

alter table "public"."inventory_checks" add constraint "inventory_checks_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_checks" validate constraint "inventory_checks_profile_fkey";

alter table "public"."inventory_checks" add constraint "inventory_checks_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_checks" validate constraint "inventory_checks_season_fkey";

grant delete on table "public"."inventory_checks" to "anon";

grant insert on table "public"."inventory_checks" to "anon";

grant references on table "public"."inventory_checks" to "anon";

grant select on table "public"."inventory_checks" to "anon";

grant trigger on table "public"."inventory_checks" to "anon";

grant truncate on table "public"."inventory_checks" to "anon";

grant update on table "public"."inventory_checks" to "anon";

grant delete on table "public"."inventory_checks" to "authenticated";

grant insert on table "public"."inventory_checks" to "authenticated";

grant references on table "public"."inventory_checks" to "authenticated";

grant select on table "public"."inventory_checks" to "authenticated";

grant trigger on table "public"."inventory_checks" to "authenticated";

grant truncate on table "public"."inventory_checks" to "authenticated";

grant update on table "public"."inventory_checks" to "authenticated";

grant delete on table "public"."inventory_checks" to "service_role";

grant insert on table "public"."inventory_checks" to "service_role";

grant references on table "public"."inventory_checks" to "service_role";

grant select on table "public"."inventory_checks" to "service_role";

grant trigger on table "public"."inventory_checks" to "service_role";

grant truncate on table "public"."inventory_checks" to "service_role";

grant update on table "public"."inventory_checks" to "service_role";

create policy "Users can delete their own inventory checks"
on "public"."inventory_checks"
as permissive
for delete
to public
using ((auth.uid() = profile));


create policy "Users can insert their own inventory checks"
on "public"."inventory_checks"
as permissive
for insert
to public
with check ((auth.uid() = profile));


create policy "Users can only see their own inventory checks"
on "public"."inventory_checks"
as permissive
for select
to public
using ((auth.uid() = profile));


create policy "Users can update their own inventory checks"
on "public"."inventory_checks"
as permissive
for update
to public
using ((auth.uid() = profile));


