create table "public"."booth_sales" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid not null,
    "season" bigint not null default 1,
    "sale_date" date not null,
    "sale_time" text,
    "location" text not null,
    "scouts_attending" text[],
    "inventory_type" text not null,
    "expected_sales" integer,
    "predicted_cookies" jsonb,
    "notes" text
);


alter table "public"."booth_sales" enable row level security;

alter table "public"."cookies" add column "percent_of_sale" double precision;

CREATE INDEX booth_sales_date_idx ON public.booth_sales USING btree (sale_date);

CREATE UNIQUE INDEX booth_sales_pkey ON public.booth_sales USING btree (id);

CREATE INDEX booth_sales_profile_idx ON public.booth_sales USING btree (profile);

CREATE INDEX booth_sales_season_idx ON public.booth_sales USING btree (season);

alter table "public"."booth_sales" add constraint "booth_sales_pkey" PRIMARY KEY using index "booth_sales_pkey";

alter table "public"."booth_sales" add constraint "booth_sales_inventory_type_check" CHECK ((inventory_type = ANY (ARRAY['troop'::text, 'scout'::text]))) not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_inventory_type_check";

alter table "public"."booth_sales" add constraint "booth_sales_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_profile_fkey";

alter table "public"."booth_sales" add constraint "booth_sales_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) ON DELETE CASCADE not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_season_fkey";

grant delete on table "public"."booth_sales" to "anon";

grant insert on table "public"."booth_sales" to "anon";

grant references on table "public"."booth_sales" to "anon";

grant select on table "public"."booth_sales" to "anon";

grant trigger on table "public"."booth_sales" to "anon";

grant truncate on table "public"."booth_sales" to "anon";

grant update on table "public"."booth_sales" to "anon";

grant delete on table "public"."booth_sales" to "authenticated";

grant insert on table "public"."booth_sales" to "authenticated";

grant references on table "public"."booth_sales" to "authenticated";

grant select on table "public"."booth_sales" to "authenticated";

grant trigger on table "public"."booth_sales" to "authenticated";

grant truncate on table "public"."booth_sales" to "authenticated";

grant update on table "public"."booth_sales" to "authenticated";

grant delete on table "public"."booth_sales" to "service_role";

grant insert on table "public"."booth_sales" to "service_role";

grant references on table "public"."booth_sales" to "service_role";

grant select on table "public"."booth_sales" to "service_role";

grant trigger on table "public"."booth_sales" to "service_role";

grant truncate on table "public"."booth_sales" to "service_role";

grant update on table "public"."booth_sales" to "service_role";

create policy "Users can delete their own booth sales"
on "public"."booth_sales"
as permissive
for delete
to public
using ((auth.uid() = profile));


create policy "Users can insert their own booth sales"
on "public"."booth_sales"
as permissive
for insert
to public
with check ((auth.uid() = profile));


create policy "Users can only see their own booth sales"
on "public"."booth_sales"
as permissive
for select
to public
using ((auth.uid() = profile));


create policy "Users can update their own booth sales"
on "public"."booth_sales"
as permissive
for update
to public
using ((auth.uid() = profile));



