
  create table "public"."deposits" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "season" bigint not null default '1'::bigint,
    "amount" numeric(10,2) not null,
    "deposit_date" date not null,
    "deposited_by" text,
    "notes" text
      );


alter table "public"."deposits" enable row level security;

CREATE INDEX deposits_deposit_date_idx ON public.deposits USING btree (deposit_date);

CREATE UNIQUE INDEX deposits_pkey ON public.deposits USING btree (id);

CREATE INDEX deposits_profile_season_idx ON public.deposits USING btree (profile, season);

alter table "public"."deposits" add constraint "deposits_pkey" PRIMARY KEY using index "deposits_pkey";

alter table "public"."deposits" add constraint "deposits_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."deposits" validate constraint "deposits_profile_fkey";

alter table "public"."deposits" add constraint "deposits_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."deposits" validate constraint "deposits_season_fkey";

grant delete on table "public"."deposits" to "anon";

grant insert on table "public"."deposits" to "anon";

grant references on table "public"."deposits" to "anon";

grant select on table "public"."deposits" to "anon";

grant trigger on table "public"."deposits" to "anon";

grant truncate on table "public"."deposits" to "anon";

grant update on table "public"."deposits" to "anon";

grant delete on table "public"."deposits" to "authenticated";

grant insert on table "public"."deposits" to "authenticated";

grant references on table "public"."deposits" to "authenticated";

grant select on table "public"."deposits" to "authenticated";

grant trigger on table "public"."deposits" to "authenticated";

grant truncate on table "public"."deposits" to "authenticated";

grant update on table "public"."deposits" to "authenticated";

grant delete on table "public"."deposits" to "service_role";

grant insert on table "public"."deposits" to "service_role";

grant references on table "public"."deposits" to "service_role";

grant select on table "public"."deposits" to "service_role";

grant trigger on table "public"."deposits" to "service_role";

grant truncate on table "public"."deposits" to "service_role";

grant update on table "public"."deposits" to "service_role";


  create policy "Allow owners/collaborators to delete their own deposits"
  on "public"."deposits"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own deposits"
  on "public"."deposits"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own deposits"
  on "public"."deposits"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own deposits"
  on "public"."deposits"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



