-- Create booth_sales table for inventory prediction
create table "public"."booth_sales" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid not null,
    "season" bigint not null default '1'::bigint,
    "sale_date" date not null,
    "sale_time" time not null,
    "location" text not null,
    "scouts_attending" text[] not null default '{}'::text[],
    "inventory_type" text not null,
    "expected_sales_level" text not null,
    "predicted_cookies" jsonb,
    "notes" text
);

alter table "public"."booth_sales" enable row level security;

CREATE UNIQUE INDEX booth_sales_pkey ON public.booth_sales USING btree (id);

alter table "public"."booth_sales" add constraint "booth_sales_pkey" PRIMARY KEY using index "booth_sales_pkey";

alter table "public"."booth_sales" add constraint "booth_sales_profile_fkey" FOREIGN KEY (profile) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_profile_fkey";

alter table "public"."booth_sales" add constraint "booth_sales_season_fkey" FOREIGN KEY (season) REFERENCES seasons(id) ON DELETE CASCADE not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_season_fkey";

alter table "public"."booth_sales" add constraint "booth_sales_inventory_type_check" CHECK ((inventory_type = ANY (ARRAY['troop'::text, 'scout'::text]))) not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_inventory_type_check";

alter table "public"."booth_sales" add constraint "booth_sales_expected_sales_level_check" CHECK ((expected_sales_level = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text]))) not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_expected_sales_level_check";

create policy "Users can delete their own booth sales"
on "public"."booth_sales"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));

create policy "Users can insert their own booth sales"
on "public"."booth_sales"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));

create policy "Users can select their own booth sales"
on "public"."booth_sales"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = profile));

create policy "Users can update their own booth sales"
on "public"."booth_sales"
as permissive
for update
to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));

-- Create indexes for performance
create index "booth_sales_profile_idx" on "public"."booth_sales" using btree (profile);
create index "booth_sales_season_idx" on "public"."booth_sales" using btree (season);
create index "booth_sales_date_idx" on "public"."booth_sales" using btree (sale_date);