
  create table "public"."deposits" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "season" bigint not null default '1'::bigint,
    "amount" numeric(10,2) not null,
    "deposit_date" date not null,
    "deposited_by" text,
    "notes" text
      );


alter table "public"."deposits" enable row level security;

alter table "public"."seasons" add column "publish_girl_request_form" boolean default false;

alter table "public"."sellers" add column "email" text;

CREATE INDEX deposits_deposit_date_idx ON public.deposits USING btree (deposit_date);

CREATE UNIQUE INDEX deposits_pkey ON public.deposits USING btree (id);

CREATE INDEX deposits_profile_season_idx ON public.deposits USING btree (profile, season);

alter table "public"."deposits" add constraint "deposits_pkey" PRIMARY KEY using index "deposits_pkey";

alter table "public"."deposits" add constraint "deposits_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."deposits" validate constraint "deposits_profile_fkey";

alter table "public"."deposits" add constraint "deposits_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."deposits" validate constraint "deposits_season_fkey";

create or replace view "public"."seller_requests" 
with (security_invoker = on) AS 
SELECT 
    s.id,
    s.first_name,
    s.season
   FROM (public.sellers s
     JOIN public.seasons se ON ((s.season = se.id)))
  WHERE (se.publish_girl_request_form = true);


grant delete on table "public"."deposits" to "anon";

grant insert on table "public"."deposits" to "anon";

grant references on table "public"."deposits" to "anon";

grant select on table "public"."deposits" to "anon";

grant trigger on table "public"."deposits" to "anon";

grant truncate on table "public"."deposits" to "anon";

grant update on table "public"."deposits" to "anon";

grant delete on table "public"."deposits" to "authenticated";

grant insert on table "public"."deposits" to "authenticated";

grant references on table "public"."deposits" to "authenticated";

grant select on table "public"."deposits" to "authenticated";

grant trigger on table "public"."deposits" to "authenticated";

grant truncate on table "public"."deposits" to "authenticated";

grant update on table "public"."deposits" to "authenticated";

grant delete on table "public"."deposits" to "service_role";

grant insert on table "public"."deposits" to "service_role";

grant references on table "public"."deposits" to "service_role";

grant select on table "public"."deposits" to "service_role";

grant trigger on table "public"."deposits" to "service_role";

grant truncate on table "public"."deposits" to "service_role";

grant update on table "public"."deposits" to "service_role";


  create policy "Allow public to view cookies for request forms"
  on "public"."cookies"
  as permissive
  for select
  to anon
using ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = cookies.season) AND (seasons.publish_girl_request_form = true)))));



  create policy "Allow owners/collaborators to delete their own deposits"
  on "public"."deposits"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own deposits"
  on "public"."deposits"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own deposits"
  on "public"."deposits"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own deposits"
  on "public"."deposits"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow public to insert cookie requests"
  on "public"."orders"
  as permissive
  for insert
  to anon
with check ((((status)::text = 'requested'::text) AND ((type)::text = 'T2G'::text) AND ("to" IN ( SELECT seller_requests.id
   FROM public.seller_requests))));



  create policy "Allow anonymous users to read seasons"
  on "public"."seasons"
  as permissive
  for select
  to anon
using (true);



  create policy "Allow public read of id, first_name, and season"
  on "public"."sellers"
  as permissive
  for select
  to public
using ((id > 0));



