drop policy "Allow users to view their own data" on "public"."seasons";


  create table "public"."season_collaborators" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "season_id" bigint not null,
    "profile_id" uuid not null,
    "invited_by" uuid not null,
    "can_edit_booths" boolean not null default false,
    "can_view_booths" boolean not null default false,
    "can_edit_inventory_checks" boolean not null default false,
    "can_view_inventory_checks" boolean not null default false
      );


alter table "public"."season_collaborators" enable row level security;


  create table "public"."seller_permissions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "collaborator_id" bigint not null,
    "seller_id" bigint not null,
    "permission_level" text not null
      );


alter table "public"."seller_permissions" enable row level security;

CREATE UNIQUE INDEX season_collaborators_pkey ON public.season_collaborators USING btree (id);

CREATE UNIQUE INDEX season_collaborators_unique ON public.season_collaborators USING btree (season_id, profile_id);

CREATE UNIQUE INDEX seller_permissions_pkey ON public.seller_permissions USING btree (id);

CREATE UNIQUE INDEX seller_permissions_unique ON public.seller_permissions USING btree (collaborator_id, seller_id);

alter table "public"."season_collaborators" add constraint "season_collaborators_pkey" PRIMARY KEY using index "season_collaborators_pkey";

alter table "public"."seller_permissions" add constraint "seller_permissions_pkey" PRIMARY KEY using index "seller_permissions_pkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_invited_by_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_profile_id_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_season_id_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_unique" UNIQUE using index "season_collaborators_unique";

alter table "public"."seller_permissions" add constraint "seller_permissions_collaborator_id_fkey" FOREIGN KEY (collaborator_id) REFERENCES public.season_collaborators(id) ON DELETE CASCADE not valid;

alter table "public"."seller_permissions" validate constraint "seller_permissions_collaborator_id_fkey";

alter table "public"."seller_permissions" add constraint "seller_permissions_permission_level_check" CHECK ((permission_level = ANY (ARRAY['none'::text, 'view'::text, 'request'::text, 'edit'::text]))) not valid;

alter table "public"."seller_permissions" validate constraint "seller_permissions_permission_level_check";

alter table "public"."seller_permissions" add constraint "seller_permissions_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES public.sellers(id) ON DELETE CASCADE not valid;

alter table "public"."seller_permissions" validate constraint "seller_permissions_seller_id_fkey";

alter table "public"."seller_permissions" add constraint "seller_permissions_unique" UNIQUE using index "seller_permissions_unique";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.is_season_collaborator(p_season_id bigint, p_profile_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.season_collaborators
    WHERE season_collaborators.season_id = p_season_id
      AND season_collaborators.profile_id = p_profile_id
  );
$function$
;

grant delete on table "public"."season_collaborators" to "anon";

grant insert on table "public"."season_collaborators" to "anon";

grant references on table "public"."season_collaborators" to "anon";

grant select on table "public"."season_collaborators" to "anon";

grant trigger on table "public"."season_collaborators" to "anon";

grant truncate on table "public"."season_collaborators" to "anon";

grant update on table "public"."season_collaborators" to "anon";

grant delete on table "public"."season_collaborators" to "authenticated";

grant insert on table "public"."season_collaborators" to "authenticated";

grant references on table "public"."season_collaborators" to "authenticated";

grant select on table "public"."season_collaborators" to "authenticated";

grant trigger on table "public"."season_collaborators" to "authenticated";

grant truncate on table "public"."season_collaborators" to "authenticated";

grant update on table "public"."season_collaborators" to "authenticated";

grant delete on table "public"."season_collaborators" to "service_role";

grant insert on table "public"."season_collaborators" to "service_role";

grant references on table "public"."season_collaborators" to "service_role";

grant select on table "public"."season_collaborators" to "service_role";

grant trigger on table "public"."season_collaborators" to "service_role";

grant truncate on table "public"."season_collaborators" to "service_role";

grant update on table "public"."season_collaborators" to "service_role";

grant delete on table "public"."seller_permissions" to "anon";

grant insert on table "public"."seller_permissions" to "anon";

grant references on table "public"."seller_permissions" to "anon";

grant select on table "public"."seller_permissions" to "anon";

grant trigger on table "public"."seller_permissions" to "anon";

grant truncate on table "public"."seller_permissions" to "anon";

grant update on table "public"."seller_permissions" to "anon";

grant delete on table "public"."seller_permissions" to "authenticated";

grant insert on table "public"."seller_permissions" to "authenticated";

grant references on table "public"."seller_permissions" to "authenticated";

grant select on table "public"."seller_permissions" to "authenticated";

grant trigger on table "public"."seller_permissions" to "authenticated";

grant truncate on table "public"."seller_permissions" to "authenticated";

grant update on table "public"."seller_permissions" to "authenticated";

grant delete on table "public"."seller_permissions" to "service_role";

grant insert on table "public"."seller_permissions" to "service_role";

grant references on table "public"."seller_permissions" to "service_role";

grant select on table "public"."seller_permissions" to "service_role";

grant trigger on table "public"."seller_permissions" to "service_role";

grant truncate on table "public"."seller_permissions" to "service_role";

grant update on table "public"."seller_permissions" to "service_role";


  create policy "Collaborators can view their own record"
  on "public"."season_collaborators"
  as permissive
  for select
  to authenticated
using ((profile_id = auth.uid()));



  create policy "Season owners can manage collaborators"
  on "public"."season_collaborators"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = auth.uid())))));



  create policy "Allow users to view their own seasons"
  on "public"."seasons"
  as permissive
  for select
  to authenticated
using (((auth.uid() = profile) OR public.is_season_collaborator(id, auth.uid())));



  create policy "Collaborators can view their own permissions"
  on "public"."seller_permissions"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.season_collaborators
  WHERE ((season_collaborators.id = seller_permissions.collaborator_id) AND (season_collaborators.profile_id = auth.uid())))));



  create policy "Season owners can manage seller permissions"
  on "public"."seller_permissions"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.season_collaborators
     JOIN public.seasons ON ((seasons.id = season_collaborators.season_id)))
  WHERE ((season_collaborators.id = seller_permissions.collaborator_id) AND (seasons.profile = auth.uid())))))
with check ((EXISTS ( SELECT 1
   FROM (public.season_collaborators
     JOIN public.seasons ON ((seasons.id = season_collaborators.season_id)))
  WHERE ((season_collaborators.id = seller_permissions.collaborator_id) AND (seasons.profile = auth.uid())))));


CREATE TRIGGER on_auth_user_insert AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


