  create table "public"."forms" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "name" character varying not null,
    "abbreviation" character varying not null,
    "url" text,
    "who" character varying not null default 'all'::character varying,
    "required" boolean not null default false,
    "season" bigint not null
      );


alter table "public"."forms" enable row level security;

alter table "public"."adults" add column "forms" bigint[] not null default '{}'::bigint[];

alter table "public"."sellers" add column "forms" bigint[] not null default '{}'::bigint[];

CREATE UNIQUE INDEX forms_pkey ON public.forms USING btree (id);

alter table "public"."forms" add constraint "forms_pkey" PRIMARY KEY using index "forms_pkey";

alter table "public"."forms" add constraint "forms_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."forms" validate constraint "forms_profile_fkey";

alter table "public"."forms" add constraint "forms_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."forms" validate constraint "forms_season_fkey";

grant references on table "public"."forms" to "anon";

grant trigger on table "public"."forms" to "anon";

grant truncate on table "public"."forms" to "anon";

grant references on table "public"."forms" to "authenticated";

grant trigger on table "public"."forms" to "authenticated";

grant truncate on table "public"."forms" to "authenticated";

grant references on table "public"."forms" to "service_role";

grant trigger on table "public"."forms" to "service_role";

grant truncate on table "public"."forms" to "service_role";


  create policy "Allow owners/collaborators to delete their own forms"
  on "public"."forms"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own forms"
  on "public"."forms"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own forms"
  on "public"."forms"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own forms"
  on "public"."forms"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



