-- Migration: Add forms table and forms columns to sellers and adults

CREATE TABLE IF NOT EXISTS "public"."forms" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "name" character varying NOT NULL,
    "abbreviation" character varying NOT NULL,
    "url" text,
    "who" character varying NOT NULL DEFAULT 'all',
    "required" boolean NOT NULL DEFAULT false,
    "season" bigint NOT NULL
);

ALTER TABLE "public"."forms" OWNER TO "postgres";

ALTER TABLE "public"."forms" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."forms_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "forms_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "forms_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."forms"
    ADD CONSTRAINT "forms_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id") ON DELETE CASCADE;

ALTER TABLE "public"."forms" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."sellers"
    ADD COLUMN IF NOT EXISTS "forms" bigint[] DEFAULT '{}'::bigint[] NOT NULL;

ALTER TABLE "public"."adults"
    ADD COLUMN IF NOT EXISTS "forms" bigint[] DEFAULT '{}'::bigint[] NOT NULL;
