CREATE TABLE IF NOT EXISTS "public"."events" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "profile" "uuid",
    "name" character varying NOT NULL,
    "start_date" date NOT NULL,
    "end_date" date NOT NULL,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "forms" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    "girls" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    "adults" bigint[] DEFAULT '{}'::bigint[] NOT NULL,
    "season" bigint NOT NULL
);

ALTER TABLE "public"."events" OWNER TO "postgres";

ALTER TABLE "public"."events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."events_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_profile_fkey" FOREIGN KEY ("profile") REFERENCES "public"."profiles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."events"
    ADD CONSTRAINT "events_season_fkey" FOREIGN KEY ("season") REFERENCES "public"."seasons"("id") ON DELETE CASCADE;

ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow owners/collaborators to view their own events" ON public.events FOR SELECT TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to delete their own events" ON public.events FOR DELETE TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to insert their own events" ON public.events FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to update their own events" ON public.events FOR UPDATE TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
