
  create table "public"."audit_sessions" (
    "id" uuid not null default gen_random_uuid(),
    "profile" uuid not null,
    "file_name" text not null,
    "file_size" integer not null,
    "created_at" timestamp with time zone not null default now(),
    "status" text not null default 'pending'::text,
    "season" bigint not null default '1'::bigint,
    "original_file_data" jsonb not null,
    "parsed_rows" jsonb not null default '[]'::jsonb
      );


alter table "public"."audit_sessions" enable row level security;


  create table "public"."booth_sales" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid not null,
    "season" bigint not null default 1,
    "sale_date" date not null,
    "sale_time" text,
    "location" text not null,
    "scouts_attending" jsonb,
    "inventory_type" text not null,
    "expected_sales" integer,
    "predicted_cookies" jsonb,
    "cookies_sold" jsonb,
    "notes" text,
    "status" text,
    "cash_receipts" double precision,
    "cash_breakdown" jsonb,
    "credit_receipts" double precision,
    "other_receipts" double precision
      );


alter table "public"."booth_sales" enable row level security;


  create table "public"."cookies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" character varying not null,
    "price" double precision,
    "color" character varying,
    "profile" uuid,
    "order" smallint,
    "abbreviation" character varying not null,
    "season" bigint not null default '1'::bigint,
    "percent_of_sale" double precision,
    "is_virtual" boolean default false,
    "overbooking_allowed" boolean default true
      );


alter table "public"."cookies" enable row level security;


  create table "public"."deposits" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "season" bigint not null default '1'::bigint,
    "amount" numeric(10,2) not null,
    "deposit_date" date not null,
    "deposited_by" text,
    "notes" text
      );


alter table "public"."deposits" enable row level security;


  create table "public"."inventory_checks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid not null,
    "season" bigint not null default 1,
    "check_date" timestamp with time zone not null default now(),
    "conducted_by" text,
    "physical_inventory" jsonb not null,
    "expected_inventory" jsonb not null,
    "discrepancies" jsonb not null,
    "total_discrepancies" integer not null default 0,
    "status" text not null default 'completed'::text,
    "notes" text
      );


alter table "public"."inventory_checks" enable row level security;


  create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "order_date" date,
    "order_num" character varying,
    "to" bigint,
    "cookies" jsonb,
    "profile" uuid,
    "season" bigint not null default '1'::bigint,
    "type" character varying,
    "status" character varying,
    "processed_date" date,
    "notes" text,
    "from" bigint,
    "supplier" text
      );


alter table "public"."orders" enable row level security;


  create table "public"."payments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "season" bigint not null default '1'::bigint,
    "seller_id" bigint not null,
    "amount" numeric(10,2) not null,
    "payment_date" date not null,
    "notes" text,
    "type" character varying
      );


alter table "public"."payments" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "updated_at" timestamp with time zone,
    "display_name" text,
    "state" jsonb,
    "season" bigint
      );


alter table "public"."profiles" enable row level security;


  create table "public"."season_collaborators" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "season_id" bigint not null,
    "profile_id" uuid not null,
    "invited_by" uuid not null,
    "can_edit_booths" boolean not null default false,
    "can_view_booths" boolean not null default false,
    "can_edit_inventory_checks" boolean not null default false,
    "can_view_inventory_checks" boolean not null default false
      );


alter table "public"."season_collaborators" enable row level security;


  create table "public"."seasons" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "troop_number" character varying not null default '0000'::character varying,
    "profile" uuid not null,
    "year" integer not null,
    "publish_girl_request_form" boolean default false
      );


alter table "public"."seasons" enable row level security;


  create table "public"."sellers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "first_name" character varying not null,
    "last_name" character varying not null,
    "preferred_name" character varying,
    "season" bigint not null default '1'::bigint,
    "email" text
      );


alter table "public"."sellers" enable row level security;


  create table "public"."uploads" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "data" jsonb,
    "profile" uuid,
    "season" bigint not null default '1'::bigint
      );


alter table "public"."uploads" enable row level security;

CREATE INDEX audit_sessions_created_at_idx ON public.audit_sessions USING btree (created_at);

CREATE UNIQUE INDEX audit_sessions_pkey ON public.audit_sessions USING btree (id);

CREATE INDEX audit_sessions_profile_idx ON public.audit_sessions USING btree (profile);

CREATE INDEX audit_sessions_status_idx ON public.audit_sessions USING btree (status);

CREATE INDEX booth_sales_date_idx ON public.booth_sales USING btree (sale_date);

CREATE UNIQUE INDEX booth_sales_pkey ON public.booth_sales USING btree (id);

CREATE INDEX booth_sales_profile_idx ON public.booth_sales USING btree (profile);

CREATE INDEX booth_sales_season_idx ON public.booth_sales USING btree (season);

CREATE UNIQUE INDEX cookies_pkey ON public.cookies USING btree (id);

CREATE INDEX deposits_deposit_date_idx ON public.deposits USING btree (deposit_date);

CREATE UNIQUE INDEX deposits_pkey ON public.deposits USING btree (id);

CREATE INDEX deposits_profile_season_idx ON public.deposits USING btree (profile, season);

CREATE INDEX inventory_checks_date_idx ON public.inventory_checks USING btree (check_date);

CREATE UNIQUE INDEX inventory_checks_pkey ON public.inventory_checks USING btree (id);

CREATE INDEX inventory_checks_profile_idx ON public.inventory_checks USING btree (profile);

CREATE INDEX inventory_checks_season_idx ON public.inventory_checks USING btree (season);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

CREATE UNIQUE INDEX payments_pkey ON public.payments USING btree (id);

CREATE INDEX payments_profile_season_idx ON public.payments USING btree (profile, season);

CREATE INDEX payments_seller_id_idx ON public.payments USING btree (seller_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX season_collaborators_pkey ON public.season_collaborators USING btree (id);

CREATE UNIQUE INDEX season_collaborators_unique ON public.season_collaborators USING btree (season_id, profile_id);

CREATE UNIQUE INDEX seasons_pkey ON public.seasons USING btree (id);

CREATE UNIQUE INDEX sellers_pkey ON public.sellers USING btree (id);

CREATE UNIQUE INDEX uploads_pkey ON public.uploads USING btree (id);

alter table "public"."audit_sessions" add constraint "audit_sessions_pkey" PRIMARY KEY using index "audit_sessions_pkey";

alter table "public"."booth_sales" add constraint "booth_sales_pkey" PRIMARY KEY using index "booth_sales_pkey";

alter table "public"."cookies" add constraint "cookies_pkey" PRIMARY KEY using index "cookies_pkey";

alter table "public"."deposits" add constraint "deposits_pkey" PRIMARY KEY using index "deposits_pkey";

alter table "public"."inventory_checks" add constraint "inventory_checks_pkey" PRIMARY KEY using index "inventory_checks_pkey";

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."payments" add constraint "payments_pkey" PRIMARY KEY using index "payments_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_pkey" PRIMARY KEY using index "season_collaborators_pkey";

alter table "public"."seasons" add constraint "seasons_pkey" PRIMARY KEY using index "seasons_pkey";

alter table "public"."sellers" add constraint "sellers_pkey" PRIMARY KEY using index "sellers_pkey";

alter table "public"."uploads" add constraint "uploads_pkey" PRIMARY KEY using index "uploads_pkey";

alter table "public"."audit_sessions" add constraint "audit_sessions_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."audit_sessions" validate constraint "audit_sessions_profile_fkey";

alter table "public"."audit_sessions" add constraint "audit_sessions_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."audit_sessions" validate constraint "audit_sessions_season_fkey";

alter table "public"."audit_sessions" add constraint "audit_sessions_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'complete'::text, 'archived'::text]))) not valid;

alter table "public"."audit_sessions" validate constraint "audit_sessions_status_check";

alter table "public"."booth_sales" add constraint "booth_sales_inventory_type_check" CHECK ((inventory_type = ANY (ARRAY['troop'::text, 'scout'::text]))) not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_inventory_type_check";

alter table "public"."booth_sales" add constraint "booth_sales_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_profile_fkey";

alter table "public"."booth_sales" add constraint "booth_sales_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_season_fkey";

alter table "public"."booth_sales" add constraint "booth_sales_status_check" CHECK (((status IS NULL) OR (status = ANY (ARRAY['archived'::text, 'committed'::text, 'recorded'::text])))) not valid;

alter table "public"."booth_sales" validate constraint "booth_sales_status_check";

alter table "public"."cookies" add constraint "cookies_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."cookies" validate constraint "cookies_profile_fkey";

alter table "public"."cookies" add constraint "cookies_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."cookies" validate constraint "cookies_season_fkey";

alter table "public"."deposits" add constraint "deposits_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."deposits" validate constraint "deposits_profile_fkey";

alter table "public"."deposits" add constraint "deposits_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."deposits" validate constraint "deposits_season_fkey";

alter table "public"."inventory_checks" add constraint "inventory_checks_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_checks" validate constraint "inventory_checks_profile_fkey";

alter table "public"."inventory_checks" add constraint "inventory_checks_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."inventory_checks" validate constraint "inventory_checks_season_fkey";

alter table "public"."orders" add constraint "orders_from_fkey" FOREIGN KEY ("from") REFERENCES public.sellers(id) ON DELETE CASCADE not valid;

alter table "public"."orders" validate constraint "orders_from_fkey";

alter table "public"."orders" add constraint "orders_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."orders" validate constraint "orders_profile_fkey";

alter table "public"."orders" add constraint "orders_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."orders" validate constraint "orders_season_fkey";

alter table "public"."orders" add constraint "orders_to_fkey" FOREIGN KEY ("to") REFERENCES public.sellers(id) ON DELETE CASCADE not valid;

alter table "public"."orders" validate constraint "orders_to_fkey";

alter table "public"."payments" add constraint "payments_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_profile_fkey";

alter table "public"."payments" add constraint "payments_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_season_fkey";

alter table "public"."payments" add constraint "payments_seller_id_fkey" FOREIGN KEY (seller_id) REFERENCES public.sellers(id) ON DELETE CASCADE not valid;

alter table "public"."payments" validate constraint "payments_seller_id_fkey";

alter table "public"."profiles" add constraint "display_name" CHECK ((char_length(display_name) >= 1)) not valid;

alter table "public"."profiles" validate constraint "display_name";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_invited_by_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_profile_id_fkey" FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_profile_id_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."season_collaborators" validate constraint "season_collaborators_season_id_fkey";

alter table "public"."season_collaborators" add constraint "season_collaborators_unique" UNIQUE using index "season_collaborators_unique";

alter table "public"."seasons" add constraint "seasons_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."seasons" validate constraint "seasons_profile_fkey";

alter table "public"."sellers" add constraint "sellers_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."sellers" validate constraint "sellers_profile_fkey";

alter table "public"."sellers" add constraint "sellers_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."sellers" validate constraint "sellers_season_fkey";

alter table "public"."uploads" add constraint "uploads_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."uploads" validate constraint "uploads_profile_fkey";

alter table "public"."uploads" add constraint "uploads_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."uploads" validate constraint "uploads_season_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (id)
  values (new.id);
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.is_season_collaborator(p_season_id bigint, p_profile_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.season_collaborators
    WHERE season_collaborators.season_id = p_season_id
      AND season_collaborators.profile_id = p_profile_id
  );
$function$
;

CREATE OR REPLACE FUNCTION public.is_season_owner(p_season_id bigint, p_profile_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
    SELECT EXISTS (
        SELECT 1 FROM public.seasons
        WHERE seasons.id = p_season_id
          AND seasons.profile = p_profile_id
    );
$function$
;

create or replace view "public"."seller_requests" as  SELECT s.id,
    s.first_name,
    s.season
   FROM (public.sellers s
     JOIN public.seasons se ON ((s.season = se.id)))
  WHERE (se.publish_girl_request_form = true);


grant delete on table "public"."audit_sessions" to "anon";

grant insert on table "public"."audit_sessions" to "anon";

grant references on table "public"."audit_sessions" to "anon";

grant select on table "public"."audit_sessions" to "anon";

grant trigger on table "public"."audit_sessions" to "anon";

grant truncate on table "public"."audit_sessions" to "anon";

grant update on table "public"."audit_sessions" to "anon";

grant delete on table "public"."audit_sessions" to "authenticated";

grant insert on table "public"."audit_sessions" to "authenticated";

grant references on table "public"."audit_sessions" to "authenticated";

grant select on table "public"."audit_sessions" to "authenticated";

grant trigger on table "public"."audit_sessions" to "authenticated";

grant truncate on table "public"."audit_sessions" to "authenticated";

grant update on table "public"."audit_sessions" to "authenticated";

grant delete on table "public"."audit_sessions" to "service_role";

grant insert on table "public"."audit_sessions" to "service_role";

grant references on table "public"."audit_sessions" to "service_role";

grant select on table "public"."audit_sessions" to "service_role";

grant trigger on table "public"."audit_sessions" to "service_role";

grant truncate on table "public"."audit_sessions" to "service_role";

grant update on table "public"."audit_sessions" to "service_role";

grant delete on table "public"."booth_sales" to "anon";

grant insert on table "public"."booth_sales" to "anon";

grant references on table "public"."booth_sales" to "anon";

grant select on table "public"."booth_sales" to "anon";

grant trigger on table "public"."booth_sales" to "anon";

grant truncate on table "public"."booth_sales" to "anon";

grant update on table "public"."booth_sales" to "anon";

grant delete on table "public"."booth_sales" to "authenticated";

grant insert on table "public"."booth_sales" to "authenticated";

grant references on table "public"."booth_sales" to "authenticated";

grant select on table "public"."booth_sales" to "authenticated";

grant trigger on table "public"."booth_sales" to "authenticated";

grant truncate on table "public"."booth_sales" to "authenticated";

grant update on table "public"."booth_sales" to "authenticated";

grant delete on table "public"."booth_sales" to "service_role";

grant insert on table "public"."booth_sales" to "service_role";

grant references on table "public"."booth_sales" to "service_role";

grant select on table "public"."booth_sales" to "service_role";

grant trigger on table "public"."booth_sales" to "service_role";

grant truncate on table "public"."booth_sales" to "service_role";

grant update on table "public"."booth_sales" to "service_role";

grant delete on table "public"."cookies" to "anon";

grant insert on table "public"."cookies" to "anon";

grant references on table "public"."cookies" to "anon";

grant select on table "public"."cookies" to "anon";

grant trigger on table "public"."cookies" to "anon";

grant truncate on table "public"."cookies" to "anon";

grant update on table "public"."cookies" to "anon";

grant delete on table "public"."cookies" to "authenticated";

grant insert on table "public"."cookies" to "authenticated";

grant references on table "public"."cookies" to "authenticated";

grant select on table "public"."cookies" to "authenticated";

grant trigger on table "public"."cookies" to "authenticated";

grant truncate on table "public"."cookies" to "authenticated";

grant update on table "public"."cookies" to "authenticated";

grant delete on table "public"."cookies" to "service_role";

grant insert on table "public"."cookies" to "service_role";

grant references on table "public"."cookies" to "service_role";

grant select on table "public"."cookies" to "service_role";

grant trigger on table "public"."cookies" to "service_role";

grant truncate on table "public"."cookies" to "service_role";

grant update on table "public"."cookies" to "service_role";

grant delete on table "public"."deposits" to "anon";

grant insert on table "public"."deposits" to "anon";

grant references on table "public"."deposits" to "anon";

grant select on table "public"."deposits" to "anon";

grant trigger on table "public"."deposits" to "anon";

grant truncate on table "public"."deposits" to "anon";

grant update on table "public"."deposits" to "anon";

grant delete on table "public"."deposits" to "authenticated";

grant insert on table "public"."deposits" to "authenticated";

grant references on table "public"."deposits" to "authenticated";

grant select on table "public"."deposits" to "authenticated";

grant trigger on table "public"."deposits" to "authenticated";

grant truncate on table "public"."deposits" to "authenticated";

grant update on table "public"."deposits" to "authenticated";

grant delete on table "public"."deposits" to "service_role";

grant insert on table "public"."deposits" to "service_role";

grant references on table "public"."deposits" to "service_role";

grant select on table "public"."deposits" to "service_role";

grant trigger on table "public"."deposits" to "service_role";

grant truncate on table "public"."deposits" to "service_role";

grant update on table "public"."deposits" to "service_role";

grant delete on table "public"."inventory_checks" to "anon";

grant insert on table "public"."inventory_checks" to "anon";

grant references on table "public"."inventory_checks" to "anon";

grant select on table "public"."inventory_checks" to "anon";

grant trigger on table "public"."inventory_checks" to "anon";

grant truncate on table "public"."inventory_checks" to "anon";

grant update on table "public"."inventory_checks" to "anon";

grant delete on table "public"."inventory_checks" to "authenticated";

grant insert on table "public"."inventory_checks" to "authenticated";

grant references on table "public"."inventory_checks" to "authenticated";

grant select on table "public"."inventory_checks" to "authenticated";

grant trigger on table "public"."inventory_checks" to "authenticated";

grant truncate on table "public"."inventory_checks" to "authenticated";

grant update on table "public"."inventory_checks" to "authenticated";

grant delete on table "public"."inventory_checks" to "service_role";

grant insert on table "public"."inventory_checks" to "service_role";

grant references on table "public"."inventory_checks" to "service_role";

grant select on table "public"."inventory_checks" to "service_role";

grant trigger on table "public"."inventory_checks" to "service_role";

grant truncate on table "public"."inventory_checks" to "service_role";

grant update on table "public"."inventory_checks" to "service_role";

grant delete on table "public"."orders" to "anon";

grant insert on table "public"."orders" to "anon";

grant references on table "public"."orders" to "anon";

grant select on table "public"."orders" to "anon";

grant trigger on table "public"."orders" to "anon";

grant truncate on table "public"."orders" to "anon";

grant update on table "public"."orders" to "anon";

grant delete on table "public"."orders" to "authenticated";

grant insert on table "public"."orders" to "authenticated";

grant references on table "public"."orders" to "authenticated";

grant select on table "public"."orders" to "authenticated";

grant trigger on table "public"."orders" to "authenticated";

grant truncate on table "public"."orders" to "authenticated";

grant update on table "public"."orders" to "authenticated";

grant delete on table "public"."orders" to "service_role";

grant insert on table "public"."orders" to "service_role";

grant references on table "public"."orders" to "service_role";

grant select on table "public"."orders" to "service_role";

grant trigger on table "public"."orders" to "service_role";

grant truncate on table "public"."orders" to "service_role";

grant update on table "public"."orders" to "service_role";

grant delete on table "public"."payments" to "anon";

grant insert on table "public"."payments" to "anon";

grant references on table "public"."payments" to "anon";

grant select on table "public"."payments" to "anon";

grant trigger on table "public"."payments" to "anon";

grant truncate on table "public"."payments" to "anon";

grant update on table "public"."payments" to "anon";

grant delete on table "public"."payments" to "authenticated";

grant insert on table "public"."payments" to "authenticated";

grant references on table "public"."payments" to "authenticated";

grant select on table "public"."payments" to "authenticated";

grant trigger on table "public"."payments" to "authenticated";

grant truncate on table "public"."payments" to "authenticated";

grant update on table "public"."payments" to "authenticated";

grant delete on table "public"."payments" to "service_role";

grant insert on table "public"."payments" to "service_role";

grant references on table "public"."payments" to "service_role";

grant select on table "public"."payments" to "service_role";

grant trigger on table "public"."payments" to "service_role";

grant truncate on table "public"."payments" to "service_role";

grant update on table "public"."payments" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."season_collaborators" to "anon";

grant insert on table "public"."season_collaborators" to "anon";

grant references on table "public"."season_collaborators" to "anon";

grant select on table "public"."season_collaborators" to "anon";

grant trigger on table "public"."season_collaborators" to "anon";

grant truncate on table "public"."season_collaborators" to "anon";

grant update on table "public"."season_collaborators" to "anon";

grant delete on table "public"."season_collaborators" to "authenticated";

grant insert on table "public"."season_collaborators" to "authenticated";

grant references on table "public"."season_collaborators" to "authenticated";

grant select on table "public"."season_collaborators" to "authenticated";

grant trigger on table "public"."season_collaborators" to "authenticated";

grant truncate on table "public"."season_collaborators" to "authenticated";

grant update on table "public"."season_collaborators" to "authenticated";

grant delete on table "public"."season_collaborators" to "service_role";

grant insert on table "public"."season_collaborators" to "service_role";

grant references on table "public"."season_collaborators" to "service_role";

grant select on table "public"."season_collaborators" to "service_role";

grant trigger on table "public"."season_collaborators" to "service_role";

grant truncate on table "public"."season_collaborators" to "service_role";

grant update on table "public"."season_collaborators" to "service_role";

grant delete on table "public"."seasons" to "anon";

grant insert on table "public"."seasons" to "anon";

grant references on table "public"."seasons" to "anon";

grant select on table "public"."seasons" to "anon";

grant trigger on table "public"."seasons" to "anon";

grant truncate on table "public"."seasons" to "anon";

grant update on table "public"."seasons" to "anon";

grant delete on table "public"."seasons" to "authenticated";

grant insert on table "public"."seasons" to "authenticated";

grant references on table "public"."seasons" to "authenticated";

grant select on table "public"."seasons" to "authenticated";

grant trigger on table "public"."seasons" to "authenticated";

grant truncate on table "public"."seasons" to "authenticated";

grant update on table "public"."seasons" to "authenticated";

grant delete on table "public"."seasons" to "service_role";

grant insert on table "public"."seasons" to "service_role";

grant references on table "public"."seasons" to "service_role";

grant select on table "public"."seasons" to "service_role";

grant trigger on table "public"."seasons" to "service_role";

grant truncate on table "public"."seasons" to "service_role";

grant update on table "public"."seasons" to "service_role";

grant delete on table "public"."sellers" to "anon";

grant insert on table "public"."sellers" to "anon";

grant references on table "public"."sellers" to "anon";

grant select on table "public"."sellers" to "anon";

grant trigger on table "public"."sellers" to "anon";

grant truncate on table "public"."sellers" to "anon";

grant update on table "public"."sellers" to "anon";

grant delete on table "public"."sellers" to "authenticated";

grant insert on table "public"."sellers" to "authenticated";

grant references on table "public"."sellers" to "authenticated";

grant select on table "public"."sellers" to "authenticated";

grant trigger on table "public"."sellers" to "authenticated";

grant truncate on table "public"."sellers" to "authenticated";

grant update on table "public"."sellers" to "authenticated";

grant delete on table "public"."sellers" to "service_role";

grant insert on table "public"."sellers" to "service_role";

grant references on table "public"."sellers" to "service_role";

grant select on table "public"."sellers" to "service_role";

grant trigger on table "public"."sellers" to "service_role";

grant truncate on table "public"."sellers" to "service_role";

grant update on table "public"."sellers" to "service_role";

grant delete on table "public"."uploads" to "anon";

grant insert on table "public"."uploads" to "anon";

grant references on table "public"."uploads" to "anon";

grant select on table "public"."uploads" to "anon";

grant trigger on table "public"."uploads" to "anon";

grant truncate on table "public"."uploads" to "anon";

grant update on table "public"."uploads" to "anon";

grant delete on table "public"."uploads" to "authenticated";

grant insert on table "public"."uploads" to "authenticated";

grant references on table "public"."uploads" to "authenticated";

grant select on table "public"."uploads" to "authenticated";

grant trigger on table "public"."uploads" to "authenticated";

grant truncate on table "public"."uploads" to "authenticated";

grant update on table "public"."uploads" to "authenticated";

grant delete on table "public"."uploads" to "service_role";

grant insert on table "public"."uploads" to "service_role";

grant references on table "public"."uploads" to "service_role";

grant select on table "public"."uploads" to "service_role";

grant trigger on table "public"."uploads" to "service_role";

grant truncate on table "public"."uploads" to "service_role";

grant update on table "public"."uploads" to "service_role";


  create policy "Allow users to delete their own audit sessions"
  on "public"."audit_sessions"
  as permissive
  for delete
  to authenticated
using ((auth.uid() = profile));



  create policy "Allow users to insert their own audit sessions"
  on "public"."audit_sessions"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = profile));



  create policy "Allow users to update their own audit sessions"
  on "public"."audit_sessions"
  as permissive
  for update
  to authenticated
using ((auth.uid() = profile));



  create policy "Allow users to view their own audit sessions"
  on "public"."audit_sessions"
  as permissive
  for select
  to authenticated
using ((auth.uid() = profile));



  create policy "Allow owners/collaborators to delete their own boothsales"
  on "public"."booth_sales"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own boothsales"
  on "public"."booth_sales"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own boothsales"
  on "public"."booth_sales"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own boothsales"
  on "public"."booth_sales"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to delete their own cookies"
  on "public"."cookies"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own cookies"
  on "public"."cookies"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own cookies"
  on "public"."cookies"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own cookies"
  on "public"."cookies"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow public to view cookies for request forms"
  on "public"."cookies"
  as permissive
  for select
  to anon
using ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = cookies.season) AND (seasons.publish_girl_request_form = true)))));



  create policy "Allow owners/collaborators to delete their own deposits"
  on "public"."deposits"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to insert their own deposits"
  on "public"."deposits"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to update their own deposits"
  on "public"."deposits"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to view their own deposits"
  on "public"."deposits"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, auth.uid()) OR public.is_season_collaborator(season, auth.uid())));



  create policy "Allow owners/collaborators to delete their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own inventory checks"
  on "public"."inventory_checks"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to delete their own orders"
  on "public"."orders"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own orders"
  on "public"."orders"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own orders"
  on "public"."orders"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own orders"
  on "public"."orders"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow public to insert cookie requests"
  on "public"."orders"
  as permissive
  for insert
  to anon
with check ((((status)::text = 'requested'::text) AND ((type)::text = 'T2G'::text) AND ("to" IN ( SELECT seller_requests.id
   FROM public.seller_requests))));



  create policy "Allow owners/collaborators to delete their own payments"
  on "public"."payments"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own payments"
  on "public"."payments"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own payments"
  on "public"."payments"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own payments"
  on "public"."payments"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Public profiles are viewable by everyone."
  on "public"."profiles"
  as permissive
  for select
  to public
using (true);



  create policy "Users can insert their own profile."
  on "public"."profiles"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = id));



  create policy "Users can update own profile."
  on "public"."profiles"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Season owners can delete collaborators"
  on "public"."season_collaborators"
  as permissive
  for delete
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = auth.uid())))));



  create policy "Season owners can insert collaborators"
  on "public"."season_collaborators"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = auth.uid())))));



  create policy "Season owners can update collaborators"
  on "public"."season_collaborators"
  as permissive
  for update
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = ( SELECT auth.uid() AS uid))))))
with check ((EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = ( SELECT auth.uid() AS uid))))));



  create policy "Season owners/collaborators can view collaborators"
  on "public"."season_collaborators"
  as permissive
  for select
  to authenticated
using (((profile_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
   FROM public.seasons
  WHERE ((seasons.id = season_collaborators.season_id) AND (seasons.profile = ( SELECT auth.uid() AS uid)))))));



  create policy "Allow anonymous users to read seasons"
  on "public"."seasons"
  as permissive
  for select
  to anon
using (true);



  create policy "Allow owners to insert their own seasons"
  on "public"."seasons"
  as permissive
  for insert
  to authenticated
with check ((profile = auth.uid()));



  create policy "Allow owners/collaborators to delete their own seasons"
  on "public"."seasons"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(id, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(id, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own seasons"
  on "public"."seasons"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(id, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(id, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own seasons"
  on "public"."seasons"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(id, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(id, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to delete their own sellers"
  on "public"."sellers"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own sellers"
  on "public"."sellers"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own sellers"
  on "public"."sellers"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own sellers"
  on "public"."sellers"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow public read of id, first_name, and season"
  on "public"."sellers"
  as permissive
  for select
  to public
using ((id > 0));



  create policy "Allow users to delete their own data"
  on "public"."uploads"
  as permissive
  for delete
  to authenticated
using ((( SELECT auth.uid() AS uid) = profile));



  create policy "Allow users to insert their own data"
  on "public"."uploads"
  as permissive
  for insert
  to authenticated
with check ((( SELECT auth.uid() AS uid) = profile));



  create policy "Allow users to update their own data"
  on "public"."uploads"
  as permissive
  for update
  to authenticated
using ((( SELECT auth.uid() AS uid) = profile))
with check ((( SELECT auth.uid() AS uid) = profile));



  create policy "Allow users to view their own data"
  on "public"."uploads"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = profile));


CREATE TRIGGER on_auth_user_insert AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


