  create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "name" character varying not null,
    "start_date" date not null,
    "end_date" date not null,
    "start_time" time without time zone,
    "end_time" time without time zone,
    "forms" bigint[] not null default '{}'::bigint[],
    "girls" bigint[] not null default '{}'::bigint[],
    "adults" bigint[] not null default '{}'::bigint[],
    "season" bigint not null
      );


alter table "public"."events" enable row level security;

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."events" add constraint "events_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_profile_fkey";

alter table "public"."events" add constraint "events_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_season_fkey";

grant references on table "public"."events" to "anon";

grant trigger on table "public"."events" to "anon";

grant truncate on table "public"."events" to "anon";

grant references on table "public"."events" to "authenticated";

grant trigger on table "public"."events" to "authenticated";

grant truncate on table "public"."events" to "authenticated";

grant references on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";


  create policy "Allow owners/collaborators to delete their own events"
  on "public"."events"
  as permissive
  for delete
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to insert their own events"
  on "public"."events"
  as permissive
  for insert
  to authenticated
with check ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to update their own events"
  on "public"."events"
  as permissive
  for update
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



  create policy "Allow owners/collaborators to view their own events"
  on "public"."events"
  as permissive
  for select
  to authenticated
using ((public.is_season_owner(season, ( SELECT auth.uid() AS uid)) OR public.is_season_collaborator(season, ( SELECT auth.uid() AS uid))));



