  create table "public"."adults" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "profile" uuid,
    "first_name" character varying not null,
    "last_name" character varying not null,
    "preferred_name" character varying,
    "season" bigint not null default '1'::bigint,
    "email" text,
    "phone" text,
    "sellers" bigint[] not null default '{}'::bigint[]
      );


alter table "public"."adults" enable row level security;

CREATE UNIQUE INDEX adults_pkey ON public.adults USING btree (id);

alter table "public"."adults" add constraint "adults_pkey" PRIMARY KEY using index "adults_pkey";

alter table "public"."adults" add constraint "adults_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."adults" validate constraint "adults_profile_fkey";

alter table "public"."adults" add constraint "adults_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."adults" validate constraint "adults_season_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.remove_deleted_seller_from_adults()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    UPDATE public.adults
    SET sellers = array_remove(sellers, OLD.id)
    WHERE OLD.id = ANY(sellers);

    RETURN OLD;
END;
$function$
;

grant references on table "public"."adults" to "anon";

grant trigger on table "public"."adults" to "anon";

grant truncate on table "public"."adults" to "anon";

grant references on table "public"."adults" to "authenticated";

grant trigger on table "public"."adults" to "authenticated";

grant truncate on table "public"."adults" to "authenticated";

grant references on table "public"."adults" to "service_role";

grant trigger on table "public"."adults" to "service_role";

grant truncate on table "public"."adults" to "service_role";

CREATE TRIGGER remove_deleted_seller_from_adults_trigger AFTER DELETE ON public.sellers FOR EACH ROW EXECUTE FUNCTION public.remove_deleted_seller_from_adults();

CREATE POLICY "Allow owners/collaborators to view their own adults" ON public.adults FOR SELECT TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to delete their own adults" ON public.adults FOR DELETE TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to insert their own adults" ON public.adults FOR INSERT TO authenticated WITH CHECK ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );
CREATE POLICY "Allow owners/collaborators to update their own adults" ON public.adults FOR UPDATE TO authenticated USING ( public.is_season_owner(season, (SELECT auth.uid())) OR public.is_season_collaborator(season, (SELECT auth.uid())) );




