create table "public"."badges" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "updated_at" timestamp with time zone not null default now(),
  "profile" uuid,
  "name" character varying not null,
  "url" text,
  "program_level" character varying not null,
  "season" bigint not null,
  constraint "badges_program_level_check" check (
    (program_level)::text = any (
      array[
        'daisy'::character varying,
        'brownie'::character varying,
        'junior'::character varying,
        'cadette'::character varying,
        'senior'::character varying,
        'ambassador'::character varying
      ]::text[]
    )
  )
);


alter table "public"."badges" enable row level security;

alter table "public"."sellers"
  add column "badges_earned" bigint[] not null default '{}'::bigint[];

alter table "public"."sellers"
  add column "badges_received" bigint[] not null default '{}'::bigint[];

CREATE UNIQUE INDEX badges_pkey ON public.badges USING btree (id);

alter table "public"."badges"
  add constraint "badges_pkey" PRIMARY KEY using index "badges_pkey";

alter table "public"."badges"
  add constraint "badges_profile_fkey" FOREIGN KEY (profile) REFERENCES public.profiles(id) ON DELETE CASCADE not valid;

alter table "public"."badges"
  validate constraint "badges_profile_fkey";

alter table "public"."badges"
  add constraint "badges_season_fkey" FOREIGN KEY (season) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."badges"
  validate constraint "badges_season_fkey";

create or replace function public.remove_deleted_badge_from_sellers()
returns trigger as $$
begin
  update public.sellers
  set
    badges_earned = array_remove(badges_earned, old.id),
    badges_received = array_remove(badges_received, old.id)
  where old.id = any(badges_earned) or old.id = any(badges_received);

  return old;
end;
$$ language plpgsql security definer;

drop trigger if exists remove_deleted_badge_from_sellers_trigger on public.badges;

create trigger remove_deleted_badge_from_sellers_trigger
  after delete on public.badges
  for each row
  execute function public.remove_deleted_badge_from_sellers();

grant references on table "public"."badges" to "anon";

grant trigger on table "public"."badges" to "anon";

grant truncate on table "public"."badges" to "anon";

grant references on table "public"."badges" to "authenticated";

grant trigger on table "public"."badges" to "authenticated";

grant truncate on table "public"."badges" to "authenticated";

grant references on table "public"."badges" to "service_role";

grant trigger on table "public"."badges" to "service_role";

grant truncate on table "public"."badges" to "service_role";

create policy "Allow owners/collaborators to delete their own badges"
on "public"."badges"
as permissive
for delete
to authenticated
using ((public.is_season_owner(season, ( select auth.uid() as uid)) OR public.is_season_collaborator(season, ( select auth.uid() as uid))));

create policy "Allow owners/collaborators to insert their own badges"
on "public"."badges"
as permissive
for insert
to authenticated
with check ((public.is_season_owner(season, ( select auth.uid() as uid)) OR public.is_season_collaborator(season, ( select auth.uid() as uid))));

create policy "Allow owners/collaborators to update their own badges"
on "public"."badges"
as permissive
for update
to authenticated
using ((public.is_season_owner(season, ( select auth.uid() as uid)) OR public.is_season_collaborator(season, ( select auth.uid() as uid))));

create policy "Allow owners/collaborators to view their own badges"
on "public"."badges"
as permissive
for select
to authenticated
using ((public.is_season_owner(season, ( select auth.uid() as uid)) OR public.is_season_collaborator(season, ( select auth.uid() as uid))));
